"""Colored dragon slayer task data."""

COLORED_DRAGONS_TASK_DATA = {
    "Black Dragons": {
        "weakness": ["Ranged", "Dragonbane"],
        "items_needed": [
            "Anti-dragon shield",
            "Dragonfire protection (anti-dragon shield + antifire potion or dragonfire shield)",
        ],
        "attack_style": "Ranged (recommended) or Melee",
        "xp_rate": 18000,
        "profit_rate": 400000,
        "recommendation": "SKIP",
        "reason": "Slow task. Better alternatives exist. Only do if killing Brutal black dragons (77 Slayer) for profit or King Black Dragon for boss task.",
        "locations": [
            {
                "name": "Taverley Dungeon",
                "requirements": ["Dragon Slayer I (partial)", "70 Slayer OR Dusty key"],
                "multi_combat": False,
                "cannon": False,
                "safespot": True,
                "notes": "Most popular location. Features safespot. Task-only area requires 70 Slayer or Dusty key. Easily accessible via Falador teleport.",
                "pros": [
                    "Safespot available",
                    "Easy access",
                    "Close to bank",
                    "Baby black dragons for quick kills",
                ],
                "cons": ["Single combat", "Can be crowded", "Slow kills"],
                "best_for": "Safespot ranged training",
            },
            {
                "name": "Evil Chicken's Lair",
                "requirements": [
                    "Dragon Slayer I (partial)",
                    "Recipe for Disaster (Freeing Sir Amik Varze)",
                    "Raw chicken in inventory",
                ],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Rarely crowded. Accessible via fairy ring code BJR. Requires raw chicken to enter.",
                "pros": ["Less crowded", "Easy access with fairy ring", "Good spawn rate"],
                "cons": ["Requires quest completion", "Single combat", "Need raw chicken"],
                "best_for": "Less crowded alternative",
            },
            {
                "name": "Corsair Cove Dungeon",
                "requirements": ["Dragon Slayer I (partial)"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Less crowded alternative. Accessible via charter ship from Rimmington.",
                "pros": ["Less crowded", "Alternative location"],
                "cons": ["Requires charter ship", "Single combat", "Further from bank"],
                "best_for": "If other locations are crowded",
            },
            {
                "name": "Wilderness Slayer Cave",
                "requirements": ["Dragon Slayer I (partial)", "Wilderness slayer"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Available for Wilderness tasks. Accessible via revenant cave scrolls. Watch for PKers.",
                "pros": ["Wilderness XP bonus", "Alternative location"],
                "cons": ["Wilderness risk (PKers)", "Dangerous", "Single combat"],
                "best_for": "Wilderness slayer tasks",
            },
            {
                "name": "Lava Maze Dungeon",
                "requirements": ["Dragon Slayer I (partial)"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Wilderness location. Accessible from Edgeville via amulet of glory. Watch for PKers.",
                "pros": ["Wilderness XP bonus"],
                "cons": ["Wilderness risk (PKers)", "Dangerous", "Single combat", "Far from bank"],
                "best_for": "Wilderness slayer only",
            },
        ],
        "alternatives": [
            {
                "name": "Baby black dragons",
                "notes": "Easily accessible in Taverley Dungeon's task-only area. Quick kills but lower profit.",
                "recommended_for": "Fast task completion",
            },
            {
                "name": "Brutal black dragons",
                "notes": "Require 77 Slayer. Most profitable variant with better drops. Located in Catacombs of Kourend.",
                "recommended_for": "High-level players (77 Slayer) for profit",
            },
            {
                "name": "King Black Dragon",
                "notes": "Boss variant. Excellent drops (Dragon pickaxe, Draconic visage). Requires good gear and supplies.",
                "recommended_for": "Boss slayer tasks",
            },
        ],
        "strategy": "Use Ranged as black dragons are weak to it. Bring anti-dragon shield and antifire potion (or dragonfire shield) for protection. Expect around 30 kills per hour. Taverley Dungeon with safespot is most popular. Consider Brutal black dragons if you have 77 Slayer for much better profit. Generally skip unless doing Brutal black dragons or KBD.",
    },
    "Black dragons": {
        "weakness": ["Ranged", "Dragonbane"],
        "items_needed": [
            "Anti-dragon shield",
            "Dragonfire protection (anti-dragon shield + antifire potion or dragonfire shield)",
        ],
        "attack_style": "Ranged (recommended) or Melee",
        "xp_rate": 18000,
        "profit_rate": 400000,
        "recommendation": "SKIP",
        "reason": "Slow task. Better alternatives exist. Only do if killing Brutal black dragons (77 Slayer) for profit or King Black Dragon for boss task.",
        "locations": [
            {
                "name": "Taverley Dungeon",
                "requirements": ["Dragon Slayer I (partial)", "70 Slayer OR Dusty key"],
                "multi_combat": False,
                "cannon": False,
                "safespot": True,
                "notes": "Most popular location. Features safespot. Task-only area requires 70 Slayer or Dusty key. Easily accessible via Falador teleport.",
                "pros": [
                    "Safespot available",
                    "Easy access",
                    "Close to bank",
                    "Baby black dragons for quick kills",
                ],
                "cons": ["Single combat", "Can be crowded", "Slow kills"],
                "best_for": "Safespot ranged training",
            },
            {
                "name": "Evil Chicken's Lair",
                "requirements": [
                    "Dragon Slayer I (partial)",
                    "Recipe for Disaster (Freeing Sir Amik Varze)",
                    "Raw chicken in inventory",
                ],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Rarely crowded. Accessible via fairy ring code BJR. Requires raw chicken to enter.",
                "pros": ["Less crowded", "Easy access with fairy ring", "Good spawn rate"],
                "cons": ["Requires quest completion", "Single combat", "Need raw chicken"],
                "best_for": "Less crowded alternative",
            },
            {
                "name": "Corsair Cove Dungeon",
                "requirements": ["Dragon Slayer I (partial)"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Less crowded alternative. Accessible via charter ship from Rimmington.",
                "pros": ["Less crowded", "Alternative location"],
                "cons": ["Requires charter ship", "Single combat", "Further from bank"],
                "best_for": "If other locations are crowded",
            },
            {
                "name": "Wilderness Slayer Cave",
                "requirements": ["Dragon Slayer I (partial)", "Wilderness slayer"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Available for Wilderness tasks. Accessible via revenant cave scrolls. Watch for PKers.",
                "pros": ["Wilderness XP bonus", "Alternative location"],
                "cons": ["Wilderness risk (PKers)", "Dangerous", "Single combat"],
                "best_for": "Wilderness slayer tasks",
            },
            {
                "name": "Lava Maze Dungeon",
                "requirements": ["Dragon Slayer I (partial)"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Wilderness location. Accessible from Edgeville via amulet of glory. Watch for PKers.",
                "pros": ["Wilderness XP bonus"],
                "cons": ["Wilderness risk (PKers)", "Dangerous", "Single combat", "Far from bank"],
                "best_for": "Wilderness slayer only",
            },
        ],
        "alternatives": [
            {
                "name": "Baby black dragons",
                "notes": "Easily accessible in Taverley Dungeon's task-only area. Quick kills but lower profit.",
                "recommended_for": "Fast task completion",
            },
            {
                "name": "Brutal black dragons",
                "notes": "Require 77 Slayer. Most profitable variant with better drops. Located in Catacombs of Kourend.",
                "recommended_for": "High-level players (77 Slayer) for profit",
            },
            {
                "name": "King Black Dragon",
                "notes": "Boss variant. Excellent drops (Dragon pickaxe, Draconic visage). Requires good gear and supplies.",
                "recommended_for": "Boss slayer tasks",
            },
        ],
        "strategy": "Use Ranged as black dragons are weak to it. Bring anti-dragon shield and antifire potion (or dragonfire shield) for protection. Expect around 30 kills per hour. Taverley Dungeon with safespot is most popular. Consider Brutal black dragons if you have 77 Slayer for much better profit. Generally skip unless doing Brutal black dragons or KBD.",
    },
    "Blue Dragons": {
        "weakness": ["Stab", "Ranged", "Dragonbane"],
        "items_needed": ["Anti-dragon shield"],
        "attack_style": "Melee (Stab) or Ranged",
        "xp_rate": 15000,
        "profit_rate": 350000,
        "recommendation": "SKIP",
        "reason": "Slow task unless killing Vorkath. Good money for lower levels but inefficient.",
        "locations": ["Taverley Dungeon", "Myths' Guild"],
    },
    "Blue dragons": {
        "weakness": ["Stab", "Ranged", "Dragonbane"],
        "items_needed": ["Anti-dragon shield"],
        "attack_style": "Melee (Stab) or Ranged",
        "xp_rate": 15000,
        "profit_rate": 350000,
        "recommendation": "SKIP",
        "reason": "Slow task unless killing Vorkath. Good money for lower levels but inefficient.",
        "locations": ["Taverley Dungeon", "Myths' Guild"],
    },
}
