"""Metal dragon slayer task data."""

METAL_DRAGONS_TASK_DATA = {
    "Adamant dragons": {
        "weakness": ["Stab", "Dragonbane"],
        "items_needed": ["Anti-dragon shield"],
        "attack_style": "Melee (Lance) or Ranged",
        "xp_rate": 10000,
        "profit_rate": 600000,
        "recommendation": "SKIP",
        "reason": "Slow task. Skip unless hunting visage or doing for collection log.",
        "locations": ["Lithkren Vault"],
    },
    "Bronze Dragons": {
        "weakness": ["Magic", "Stab", "Dragonbane"],
        "items_needed": [
            "Anti-dragon shield",
            "Dragonfire protection (anti-dragon shield + antifire potion or dragonfire shield)",
        ],
        "attack_style": "Magic (Trident/Sang) or Melee (Dragon hunter lance)",
        "xp_rate": 12000,
        "profit_rate": 80000,
        "recommendation": "SKIP",
        "reason": "Very slow, low profit. Weakest metal dragons but still inefficient. No visage drop unlike other metal dragons.",
        "locations": [
            {
                "name": "Brimhaven Dungeon",
                "requirements": [
                    "Dragon Slayer I (partial)",
                    "875 GP entry fee (north) OR 5,000 trading sticks (south, one-time)",
                ],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "8 total spawns - 3 in regular area, 5 in task-only section. Fastest access via house teleport or Tai Bwo Wanni teleport.",
                "pros": ["Task-only section available", "Multiple spawns", "Easy access"],
                "cons": [
                    "Entry fee required",
                    "Single combat",
                    "Very slow kills",
                    "No visage drop",
                ],
                "best_for": "If forced to do bronze dragons",
            },
            {
                "name": "Catacombs of Kourend",
                "requirements": [
                    "Dragon Slayer I (partial)",
                    "100% Kourend favour OR Xeric's Heart teleport",
                ],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "3 spawns. Accessible via Xeric's Heart teleport (requires 100% favour), Kourend teleport, or Xeric's Glade teleport.",
                "pros": ["Prayer restoration from bones", "Totem pieces", "Ancient shards"],
                "cons": ["Fewer spawns", "Requires favour", "Very slow kills", "No visage drop"],
                "best_for": "If you need prayer restoration",
            },
        ],
        "alternatives": [],
        "strategy": "Use Magic (Trident/Sang) or Melee with Dragon hunter lance. Bring anti-dragon shield and antifire potion (or dragonfire shield). Protect from Magic doesn't work against metal dragon dragonfire. Bronze dragons are the weakest metal dragons but still very slow. They don't drop Draconic Visage like other metal dragons, making them less popular. Generally skip this task.",
    },
    "Bronze dragons": {
        "weakness": ["Magic", "Stab", "Dragonbane"],
        "items_needed": [
            "Anti-dragon shield",
            "Dragonfire protection (anti-dragon shield + antifire potion or dragonfire shield)",
        ],
        "attack_style": "Magic (Trident/Sang) or Melee (Dragon hunter lance)",
        "xp_rate": 12000,
        "profit_rate": 80000,
        "recommendation": "SKIP",
        "reason": "Very slow, low profit. Weakest metal dragons but still inefficient. No visage drop unlike other metal dragons.",
        "locations": [
            {
                "name": "Brimhaven Dungeon",
                "requirements": [
                    "Dragon Slayer I (partial)",
                    "875 GP entry fee (north) OR 5,000 trading sticks (south, one-time)",
                ],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "8 total spawns - 3 in regular area, 5 in task-only section. Fastest access via house teleport or Tai Bwo Wanni teleport.",
                "pros": ["Task-only section available", "Multiple spawns", "Easy access"],
                "cons": [
                    "Entry fee required",
                    "Single combat",
                    "Very slow kills",
                    "No visage drop",
                ],
                "best_for": "If forced to do bronze dragons",
            },
            {
                "name": "Catacombs of Kourend",
                "requirements": [
                    "Dragon Slayer I (partial)",
                    "100% Kourend favour OR Xeric's Heart teleport",
                ],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "3 spawns. Accessible via Xeric's Heart teleport (requires 100% favour), Kourend teleport, or Xeric's Glade teleport.",
                "pros": ["Prayer restoration from bones", "Totem pieces", "Ancient shards"],
                "cons": ["Fewer spawns", "Requires favour", "Very slow kills", "No visage drop"],
                "best_for": "If you need prayer restoration",
            },
        ],
        "alternatives": [],
        "strategy": "Use Magic (Trident/Sang) or Melee with Dragon hunter lance. Bring anti-dragon shield and antifire potion (or dragonfire shield). Protect from Magic doesn't work against metal dragon dragonfire. Bronze dragons are the weakest metal dragons but still very slow. They don't drop Draconic Visage like other metal dragons, making them less popular. Generally skip this task.",
    },
    "Iron Dragons": {
        "weakness": ["Magic", "Stab", "Dragonbane"],
        "items_needed": ["Anti-dragon shield"],
        "attack_style": "Magic (Trident/Sang)",
        "xp_rate": 12000,
        "profit_rate": 100000,
        "recommendation": "SKIP",
        "reason": "Very slow. Skip.",
        "locations": ["Brimhaven Dungeon", "Catacombs of Kourend"],
    },
    "Iron dragons": {
        "weakness": ["Magic", "Stab", "Dragonbane"],
        "items_needed": ["Anti-dragon shield"],
        "attack_style": "Magic (Trident/Sang)",
        "xp_rate": 12000,
        "profit_rate": 100000,
        "recommendation": "SKIP",
        "reason": "Very slow. Skip.",
        "locations": ["Brimhaven Dungeon", "Catacombs of Kourend"],
    },
    "Mithril dragons": {
        "weakness": ["Stab", "Dragonbane"],
        "items_needed": ["Anti-dragon shield"],
        "attack_style": "Melee (Lance) or Ranged",
        "xp_rate": 8000,
        "profit_rate": 500000,
        "recommendation": "SKIP",
        "reason": "Very slow, high defence. Only do if hunting visage (rare drop).",
        "locations": ["Ancient Cavern"],
    },
    "Rune dragons": {
        "weakness": ["Stab", "Dragonbane"],
        "items_needed": ["Anti-dragon shield", "Dragonfire protection"],
        "attack_style": "Melee (Lance) or Ranged",
        "xp_rate": 12000,
        "profit_rate": 1500000,
        "recommendation": "DO",
        "reason": "Excellent profit from rune dragon bones and rare drops. Slow but worth it.",
        "locations": ["Lithkren Vault"],
    },
    "Steel Dragons": {
        "weakness": ["Magic", "Stab", "Dragonbane"],
        "items_needed": ["Anti-dragon shield"],
        "attack_style": "Magic (Trident/Sang)",
        "xp_rate": 10000,
        "profit_rate": 150000,
        "recommendation": "SKIP",
        "reason": "Very slow, high defence. Skip unless hunting visage (inefficient).",
        "locations": ["Brimhaven Dungeon", "Catacombs of Kourend"],
    },
    "Steel dragons": {
        "weakness": ["Magic", "Stab", "Dragonbane"],
        "items_needed": ["Anti-dragon shield"],
        "attack_style": "Magic (Trident/Sang)",
        "xp_rate": 10000,
        "profit_rate": 150000,
        "recommendation": "SKIP",
        "reason": "Very slow, high defence. Skip unless hunting visage (inefficient).",
        "locations": ["Brimhaven Dungeon", "Catacombs of Kourend"],
    },
}
