"""Beasts slayer task data."""

BEASTS_TASK_DATA = {
    "Hellhounds": {
        "weakness": ["Slash"],
        "items_needed": [],
        "attack_style": "Melee",
        "xp_rate": 25000,
        "profit_rate": 0,
        "recommendation": "SKIP",
        "reason": "Low XP and no drops unless doing Cerberus (Boss). Skip if not bossing.",
        "locations": [
            {
                "name": "Stronghold Slayer Cave",
                "requirements": [],
                "multi_combat": True,
                "cannon": True,
                "safespot": False,
                "notes": "Best spot for cannon. Still not worth doing unless bossing.",
                "pros": ["Cannon allowed", "Easy access"],
                "cons": ["Zero drops", "Waste of cannonballs"],
                "best_for": "Skip this task",
            },
            {
                "name": "Catacombs of Kourend",
                "requirements": ["20% Arceuus favour"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Prayer restoration but still not worth it.",
                "pros": ["Prayer restoration", "Totem pieces"],
                "cons": ["No drops", "Slow"],
                "best_for": "Skip this task",
            },
        ],
        "alternatives": [
            {
                "name": "Cerberus",
                "notes": "Boss variant requires 91 Slayer. Excellent drops (Primordial/Pegasian/Eternal crystals).",
                "recommended_for": "High-level players only. Otherwise skip task.",
            }
        ],
        "strategy": "Skip unless you can kill Cerberus (91 Slayer). If forced to do regular hellhounds, cannon in Stronghold for fastest completion.",
    },
    "Waterfiends": {
        "weakness": ["Crush", "Earth magic (100% weakness)"],
        "items_needed": [
            "Crush weapon (abyssal bludgeon, Sarachnis cudgel, leaf-bladed battleaxe, dragon mace)",
            "Magic defence armor (Dragonhide, Karil's, Eclipse Moon)",
        ],
        "attack_style": "Melee (Crush) or Magic (Earth spells) or Ranged",
        "xp_rate": 25000,
        "profit_rate": 200000,
        "recommendation": "DO",
        "reason": "Reasonable task with good charm drops (crimson charms for summoning). Decent XP and profit with crush weapons.",
        "locations": [
            {
                "name": "Ancient Cavern",
                "requirements": ["75 Combat", "Must enter Ancient Cavern once before assignment"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Most common location. Access via whirlpool at Baxtorian Falls. Multi-combat area. Waterfiends attack with Magic and magical Ranged (both roll against Magic Defence).",
                "pros": [
                    "Most common location",
                    "Multicombat",
                    "Good spawn density",
                    "Crimson charm drops",
                    "Water orbs and bones",
                ],
                "cons": [
                    "Requires entering cavern first",
                    "No cannon",
                    "Magic attacks can't be fully protected",
                ],
                "best_for": "Charm farming and slayer XP",
            },
            {
                "name": "Kraken Cove",
                "requirements": ["75 Combat"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Alternative location. Less common than Ancient Cavern.",
                "pros": ["Alternative location", "Multicombat"],
                "cons": ["Less common", "No cannon"],
                "best_for": "Alternative if Ancient Cavern unavailable",
            },
            {
                "name": "Iorwerth Dungeon",
                "requirements": ["75 Combat", "Song of the Elves quest"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Requires high-level quest completion. Good spawn density.",
                "pros": ["Good spawn density", "Crystal shards nearby", "Multicombat"],
                "cons": ["High quest requirement", "No cannon"],
                "best_for": "Post-quest alternative",
            },
        ],
        "alternatives": [],
        "strategy": "Use crush weapons (abyssal bludgeon, Sarachnis cudgel, leaf-bladed battleaxe, or dragon mace) due to waterfiends' low crush defence. Alternatively use earth spells (100% weakness) or ranged. Wear Magic Defence armor (Dragonhide, Karil's, or Eclipse Moon). Use Protect from Missiles if taking heavy damage, or Mystic Might for magic bonus. Bring high-healing food (sharks or anglerfish). Waterfiends drop crimson charms (valuable for summoning), water orbs, and bones.",
    },
}
