"""Catacombs slayer task data."""

CATACOMBS_TASK_DATA = {
    "Dust devils": {
        "weakness": [],
        "items_needed": ["Facemask/Slayer Helmet"],
        "attack_style": "Magic (Burst/Barrage)",
        "xp_rate": 65000,
        "profit_rate": 200000,
        "recommendation": "DO",
        "reason": "One of the best XP tasks in the game when bursting. Very profitable too.",
        "locations": [
            {
                "name": "Catacombs of Kourend",
                "requirements": ["20% Arceuus favour"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Best location for bursting. Stack dust devils in corner for maximum efficiency.",
                "pros": [
                    "Prayer restoration",
                    "Totem pieces",
                    "Ancient shards",
                    "Superior encounters",
                    "Perfect for bursting",
                ],
                "cons": ["Requires favour", "Need to navigate to location"],
                "best_for": "Bursting for maximum XP/hr",
            },
            {
                "name": "Smoke Dungeon",
                "requirements": ["Desert Treasure quest (for Pollnivneach entrance)"],
                "multi_combat": False,
                "cannon": True,
                "safespot": True,
                "notes": "Single-way combat. Can use cannon but not ideal for bursting.",
                "pros": ["Cannon allowed", "Safespot available"],
                "cons": ["Single combat", "Not ideal for bursting", "Requires desert treasure"],
                "best_for": "Solo cannon slayer (not recommended)",
            },
        ],
        "alternatives": [],
        "strategy": "Always burst in Catacombs. Stack 9+ dust devils in corner, use Ice Barrage. Bring Slayer Helmet (i) for magic bonus. Prayer gear recommended.",
    },
    "Bloodveld": {
        "weakness": [],
        "items_needed": [],
        "attack_style": "Melee (Cannon) or Magic (Burst/Barrage)",
        "xp_rate": 45000,
        "profit_rate": 100000,
        "recommendation": "DO",
        "reason": "Great XP, especially mutated variants in Catacombs. Low profit but fast.",
        "locations": [
            {
                "name": "Catacombs of Kourend",
                "requirements": ["20% Arceuus favour"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Mutated Bloodvelds. Best for bursting. Prayer restoration from bones.",
                "pros": [
                    "Prayer restoration",
                    "Mutated variants",
                    "Superior encounters",
                    "Totem pieces",
                ],
                "cons": ["Requires favour"],
                "best_for": "Bursting for maximum XP",
            },
            {
                "name": "Stronghold Slayer Cave",
                "requirements": [],
                "multi_combat": True,
                "cannon": True,
                "safespot": False,
                "notes": "Good for cannon. Close to bank via Ring of Slaying.",
                "pros": ["Cannon allowed", "Easy access with Ring of Slaying", "No requirements"],
                "cons": ["No prayer restoration", "Regular bloodvelds only"],
                "best_for": "Cannon slayer training",
            },
            {
                "name": "Meiyerditch Laboratories",
                "requirements": ["Sins of the Father quest"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Vyrewatch Sentinels count as bloodvelds. Very high profit.",
                "pros": ["Excellent profit", "Blood shards", "Counts for bloodveld task"],
                "cons": ["High quest requirement", "Single combat", "Slower than bursting"],
                "best_for": "Profit-focused players post-quest",
            },
        ],
        "alternatives": [],
        "strategy": "Burst mutated bloodvelds in Catacombs for XP. Use cannon in Stronghold for casual slayer. Do Vyrewatch Sentinels if you need GP.",
    },
}
