"""Demons slayer task data."""

DEMONS_TASK_DATA = {
    "Abyssal demons": {
        "weakness": ["Slash", "Demonbane"],
        "items_needed": [],
        "attack_style": "Melee (Slash) or Magic (Burst/Barrage)",
        "xp_rate": 35000,
        "profit_rate": 400000,
        "recommendation": "DO",
        "reason": "Great combat XP and chance for Abyssal Whip. Barraging in Catacombs is very high XP.",
        "locations": [
            {
                "name": "Slayer Tower",
                "requirements": [],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Most popular location. Top floor has many spawns.",
                "pros": ["Close to Canifis bank", "Many spawn points", "Easy access"],
                "cons": ["Can be crowded on peak hours"],
                "best_for": "Melee training or casual slayer",
            },
            {
                "name": "Catacombs of Kourend",
                "requirements": ["20% Arceuus favour"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Restores prayer via bone drops. Superior encounters possible. Drops ancient shards and totem pieces.",
                "pros": [
                    "Prayer restoration",
                    "Totem pieces",
                    "Ancient shards",
                    "Superior encounters",
                    "Excellent for bursting/barraging",
                ],
                "cons": [
                    "Requires Arceuus favour",
                    "Further from bank",
                    "Need to navigate dungeon",
                ],
                "best_for": "Bursting/barraging for maximum XP and superior encounters",
            },
        ],
        "alternatives": [],
        "strategy": "Use Arclight for +70% damage bonus against demons. For maximum XP, barrage in Catacombs. For afk melee, use Slayer Tower with guthan's or blood barrage for healing.",
    },
    "Nechryael": {
        "weakness": ["Demonbane", "Crush"],
        "items_needed": [],
        "attack_style": "Magic (Burst/Barrage)",
        "xp_rate": 55000,
        "profit_rate": 300000,
        "recommendation": "DO",
        "reason": "Incredible XP/hr when bursting in Catacombs. Break-even or profitable with drops.",
        "locations": [
            {
                "name": "Catacombs of Kourend",
                "requirements": ["20% Arceuus favour"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Best location. Death spawns stack nicely for bursting. Greater Nechryael possible.",
                "pros": [
                    "Prayer restoration",
                    "Totem pieces",
                    "Superior encounters (Greater Nechryael)",
                    "Death spawns for extra XP",
                ],
                "cons": ["Requires favour", "Need to manage death spawns"],
                "best_for": "Bursting for maximum XP/hr",
            },
            {
                "name": "Slayer Tower",
                "requirements": [],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Alternative location but less efficient than Catacombs.",
                "pros": ["Easy access", "No requirements"],
                "cons": [
                    "No prayer restoration",
                    "Less efficient spawns",
                    "No superior encounters",
                ],
                "best_for": "If Arceuus favour not obtained",
            },
            {
                "name": "Iorwerth Dungeon",
                "requirements": ["Song of the Elves quest"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Good spawn density. Requires high-level quest completion.",
                "pros": ["Good spawn density", "Crystal shards from elves nearby"],
                "cons": ["High quest requirement", "Further from bank"],
                "best_for": "Post-quest alternative to Catacombs",
            },
        ],
        "alternatives": [],
        "strategy": "Burst in Catacombs for best XP. Let death spawns stack, then barrage them all. Use Arclight for melee if low on runes. Slayer Helmet (i) highly recommended.",
    },
}
