"""Misc slayer task data - Part 2."""

MISC_TASK_DATA_PART2 = {
    "Brine rats": {
        "weakness": ["Rat bone weapons (Bone mace/Bone shortbow/Bone staff)"],
        "items_needed": [
            "Spade (to enter cavern)",
            "Rat bone weapons recommended (adds +10 max hit)",
        ],
        "attack_style": "Melee (Cannon) or Melee (Bone mace) or Ranged (Bone shortbow) or Magic (Bone staff)",
        "xp_rate": 15000,
        "profit_rate": 100000,
        "recommendation": "SKIP",
        "reason": "Low XP, low profit. Only notable for medium clues and rare brine sabre drop. Generally inefficient.",
        "locations": [
            {
                "name": "Brine Rat Cavern (Sven's cave)",
                "requirements": ["47 Slayer", "Olaf's Quest (partial completion)"],
                "multi_combat": False,
                "cannon": True,
                "safespot": False,
                "notes": "Only location for Brine rats. Access by digging south of windswept tree with spade. Falls through and gets stunned briefly. Dwarf multicannons allowed.",
                "pros": [
                    "Cannon allowed",
                    "Medium clue drops",
                    "Rare brine sabre drop",
                    "Rat bone weapons add +10 max hit",
                ],
                "cons": [
                    "Low XP",
                    "Low profit",
                    "Only one location",
                    "Requires quest",
                    "Single combat",
                ],
                "best_for": "Medium clue hunting or brine sabre collection",
            }
        ],
        "alternatives": [],
        "strategy": "Use rat bone weapons (Bone mace for melee, Bone shortbow for ranged, Bone staff for magic) for +10 max hit bonus. These weapons only work against rats. Cannon is allowed and speeds up task. Bring spade to enter cavern. Best accessed via Fairy ring code DKS (requires Fairytale II) or Eagle transport to Rellekka. Generally skip unless hunting medium clues or brine sabre.",
    },
    "Trolls": {
        "weakness": ["Crush", "Stab"],
        "items_needed": ["Neitiznot shield (for Ice Trolls)", "Dwarf multicannon"],
        "attack_style": "Melee (Cannon) - Crush or Stab recommended",
        "xp_rate": 40000,
        "profit_rate": 150000,
        "recommendation": "DO",
        "reason": "Excellent cannon task with Ice Trolls. High XP rates and decent profit from rune items and granite shields.",
        "locations": [
            {
                "name": "Jatizso (Ice Trolls)",
                "requirements": ["Fremennik Isles quest", "Dwarf Cannon quest", "60 Combat"],
                "multi_combat": True,
                "cannon": True,
                "safespot": False,
                "notes": "Best location. Cannon Ice Trolls on Jatizso island (not in caves - caves don't allow cannon). Multi-combat zone. Fastest access via Enchanted Lyre (after Elite Fremennik Diary).",
                "pros": [
                    "Cannon allowed",
                    "Multicombat",
                    "High XP rates",
                    "Decent profit",
                    "Rune items and granite shield drops",
                ],
                "cons": [
                    "Requires Fremennik Isles quest",
                    "Requires cannon quest",
                    "Uses cannonballs",
                ],
                "best_for": "Fast XP with cannon",
            },
            {
                "name": "Death Plateau",
                "requirements": ["60 Combat"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "15 level 69 Mountain Trolls. Access via Games Necklace to Burthorpe, then walk northwest. Use Protect from Ranged while traveling.",
                "pros": ["Easy access", "No quest requirements", "Close to teleport"],
                "cons": ["Single combat", "No cannon", "Lower spawn count"],
                "best_for": "If Fremennik Isles not completed",
            },
            {
                "name": "Mount Quidamortem",
                "requirements": ["60 Combat", "Xeric's talisman"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Alternative mountain troll location. Accessible with Xeric's talisman.",
                "pros": ["Alternative location", "Xeric's talisman access"],
                "cons": ["Single combat", "No cannon", "Further from bank"],
                "best_for": "Alternative if other locations unavailable",
            },
        ],
        "alternatives": [
            {
                "name": "Ice Troll King",
                "notes": "Boss variant in Ice Troll Caves. Requires good gear.",
                "recommended_for": "Boss slayer tasks",
            }
        ],
        "strategy": "Use crush or stab weapons (Ice Trolls are slightly slash-resistant). Cannon Ice Trolls on Jatizso island for best XP rates. Wear Neitiznot shield to reduce ranged max hits. Ice Troll Caves don't allow cannons due to dank air - cannon on the island instead. Expect high XP rates and decent profit from rune items and granite shields.",
    },
    "Elves": {
        "weakness": ["Ranged", "Stab"],
        "items_needed": [
            "Dwarf multicannon (for Iorwerth Dungeon)",
            "Song of the Elves quest completion (highly recommended)",
        ],
        "attack_style": "Melee (Cannon) or Ranged or Melee (Stab)",
        "xp_rate": 30000,
        "profit_rate": 500000,
        "recommendation": "SKIP",
        "reason": "BLOCK until Song of the Elves is completed. After quest, Iorwerth Dungeon becomes excellent with cannon, Enhanced crystal teleport seeds (~1.9M), and crystal shards. Without quest, all locations are terrible.",
        "locations": [
            {
                "name": "Iorwerth Dungeon",
                "requirements": [
                    "70 Combat",
                    "Regicide quest",
                    "Song of the Elves quest (REQUIRED)",
                ],
                "multi_combat": False,
                "cannon": True,
                "safespot": False,
                "notes": "BEST location after Song of the Elves. Found in Prifddinas' south-west district. 13 Iorwerth Warriors (level 108). Cannon can be effectively used. No cluttered terrain. Drops Enhanced crystal teleport seeds (worth ~1.9M) and 3-5 crystal shards per kill.",
                "pros": [
                    "Cannon allowed",
                    "Excellent profit (Enhanced crystal teleport seeds)",
                    "Crystal shards (3-5 per kill)",
                    "Good spawn density",
                    "No terrain obstacles",
                ],
                "cons": [
                    "Requires Song of the Elves quest",
                    "High quest requirement",
                    "Single combat",
                ],
                "best_for": "Post-quest cannon slayer with excellent profit",
            },
            {
                "name": "Iorwerth Camp",
                "requirements": ["70 Combat", "Regicide quest"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "6 archers and 6 warriors. Cannon placement hindered by tents, barrels, and crates. Terrible location.",
                "pros": ["No Song of the Elves required"],
                "cons": [
                    "Cannon ineffective (obstacles)",
                    "Few spawns",
                    "Far from bank",
                    "Poor drops",
                    "Cluttered terrain",
                ],
                "best_for": "NOT RECOMMENDED - Block this task instead",
            },
            {
                "name": "Lletya",
                "requirements": ["70 Combat", "Regicide quest"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Only 1 archer and 2 warriors. Very few spawns.",
                "pros": ["No Song of the Elves required"],
                "cons": ["Very few spawns", "Far from bank", "No cannon", "Terrible location"],
                "best_for": "NOT RECOMMENDED - Block this task instead",
            },
            {
                "name": "Prifddinas",
                "requirements": ["70 Combat", "Regicide quest", "Song of the Elves quest"],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Scattered elves throughout the city. Not efficient.",
                "pros": ["In Prifddinas"],
                "cons": [
                    "Scattered spawns",
                    "No cannon",
                    "Inefficient",
                    "Requires Song of the Elves anyway",
                ],
                "best_for": "NOT RECOMMENDED - Use Iorwerth Dungeon instead",
            },
        ],
        "alternatives": [],
        "strategy": "BLOCK this task until you complete Song of the Elves quest. After quest, use cannon in Iorwerth Dungeon for excellent XP and profit. Elves are weakest to ranged and stab. Use overhead prayers, cannon, and high-tier gear. Iorwerth Warriors drop Enhanced crystal teleport seeds (worth ~1.9M) and 3-5 crystal shards per kill. Without Song of the Elves, all locations are terrible - block the task.",
    },
    "Mutated zygomites": {
        "weakness": ["Magic defence"],
        "items_needed": [
            "Fungicide spray (MANDATORY - cannot kill without it)",
            "Fungicide for refills (300 coins from Slayer Master, 10 coins per refill)",
        ],
        "attack_style": "Melee (recommended) or Ranged",
        "xp_rate": 20000,
        "profit_rate": 150000,
        "recommendation": "DO",
        "reason": "Good herb and seed drops (especially for Ironmen). Low defence and HP make them quick to kill. Decent profit from herbs.",
        "locations": [
            {
                "name": "Zanaris (East of Furnace)",
                "requirements": ["57 Slayer", "Lost City quest"],
                "multi_combat": False,
                "cannon": False,
                "safespot": True,
                "notes": "Level 74 Mutated Zygomites. Pick up fungi to initiate combat. Can safespot using pillars. Fungicide spray required to finish every kill (10 charges per spray).",
                "pros": [
                    "Low defence and HP",
                    "Good herb drops (ranarr, tarromin, snapdragon)",
                    "Seed drops",
                    "Safespot available",
                    "Quick kills",
                ],
                "cons": [
                    "Requires fungicide spray (mandatory)",
                    "Spray needs recharging after 10 kills",
                    "Inventory management overhead",
                ],
                "best_for": "Herb farming and seed collection (especially Ironmen)",
            },
            {
                "name": "Zanaris (Near Cosmic Altar)",
                "requirements": ["57 Slayer", "Lost City quest"],
                "multi_combat": False,
                "cannon": False,
                "safespot": True,
                "notes": "Level 86 Mutated Zygomites. Can safespot using pillars near Cosmic Altar. Fungicide spray required to finish every kill.",
                "pros": [
                    "Higher level variant",
                    "Safespot available",
                    "Good herb drops",
                    "Near Cosmic Altar",
                ],
                "cons": [
                    "Requires fungicide spray (mandatory)",
                    "Spray needs recharging",
                    "Inventory management",
                ],
                "best_for": "Herb farming with safespot",
            },
        ],
        "alternatives": [],
        "strategy": "Pick up fungi to initiate combat, attack the Zygomite, and once HP reaches zero, use fungicide spray to finish the kill. Wear dragonhide or high magic defence armor (they use magic-based attacks). Fungicide spray has 10 charges and can be refilled with Fungicide (300 coins from Slayer Master, 10 coins per refill). Zygomites commonly drop fungicide refills. Unlock 'Shroom Sprayer' (110 Slayer Points) to automatically apply fungicide. Safespot using pillars for safe kills.",
    },
}
