"""Undead slayer task data."""

UNDEAD_TASK_DATA = {
    "Ankou": {
        "weakness": ["Salve amulet (undead)"],
        "items_needed": [],
        "attack_style": "Melee (Cannon)",
        "xp_rate": 30000,
        "profit_rate": 200000,
        "recommendation": "DO",
        "reason": "Fast task with good death and blood rune drops. Decent profit and XP with cannon.",
        "locations": [
            {
                "name": "Catacombs of Kourend",
                "requirements": ["20% Arceuus favour"],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "Recommended location. 10 Ankou spawns. Multicombat area allows AFK time. Access via POH portal, Kharedst's memoirs, or fairy ring CIS.",
                "pros": [
                    "Multicombat",
                    "Prayer restoration from bones",
                    "Totem pieces",
                    "Ancient shards",
                    "AFK friendly",
                ],
                "cons": ["Requires Arceuus favour", "No cannon"],
                "best_for": "AFK slayer with prayer restoration",
            },
            {
                "name": "Stronghold Slayer Cave",
                "requirements": [],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "8 Ankou spawns (levels 75, 82, 86). Fast access via Slayer Ring or spirit tree from Grand Exchange.",
                "pros": ["Easy access with Slayer Ring", "No requirements", "Close to bank"],
                "cons": ["Single combat", "Lower spawn count", "No cannon"],
                "best_for": "Quick task completion",
            },
            {
                "name": "Sepulchre of Death (Stronghold of Security)",
                "requirements": [],
                "multi_combat": False,
                "cannon": False,
                "safespot": False,
                "notes": "Largest concentration with 32 Ankou spawns. Located in Barbarian Village.",
                "pros": ["Highest spawn count", "No requirements", "Easy access"],
                "cons": ["Single combat", "No cannon", "Further from bank"],
                "best_for": "Maximum spawn density",
            },
            {
                "name": "Wilderness Slayer Cave",
                "requirements": [],
                "multi_combat": True,
                "cannon": False,
                "safespot": False,
                "notes": "16 level 98 Ankou spawns in multicombat. Access via Ferox Enclave teleport then run east. Watch for PKers (many below level 30 Wilderness).",
                "pros": ["Multicombat", "High level Ankous", "Good spawn count"],
                "cons": ["Wilderness risk (PKers)", "No cannon", "Dangerous"],
                "best_for": "Risk-tolerant players",
            },
            {
                "name": "The Forgotten Cemetery",
                "requirements": [],
                "multi_combat": False,
                "cannon": True,
                "safespot": False,
                "notes": "Wilderness location with normal Ankous in singles area. Cannon can be placed but watch for PKers.",
                "pros": ["Cannon allowed", "Wilderness XP bonus"],
                "cons": ["Wilderness risk (PKers)", "Single combat", "Dangerous"],
                "best_for": "Cannon slayer in Wilderness",
            },
        ],
        "alternatives": [],
        "strategy": "Use Protect from Melee to negate all damage. Ankous are undead so Salve amulet works but doesn't stack with Slayer helmet. Melee is cheapest. Catacombs is best for AFK with prayer restoration. Stronghold Slayer Cave for quick access. Use cannon in Forgotten Cemetery if doing Wilderness slayer.",
    },
}
