"""{category_name} monster definitions."""

from backend.models import Monster


def get_beast_monsters() -> list[Monster]:
    """Get {category_name} monster definitions."""
    return [
        Monster(
            id=5361,
            name="Waterfiend",
            combat_level=115,
            hitpoints=95,
            slayer_xp=128,
            slayer_category="Waterfiends",
        ),
        Monster(
            id=5361,
            name="Waterfiend",
            combat_level=115,
            hitpoints=95,
            slayer_xp=128,
            slayer_category="Waterfiends",
        ),
        Monster(
            id=5361,
            name="Waterfiend",
            combat_level=115,
            hitpoints=95,
            slayer_xp=128,
            slayer_category="Waterfiends",
        ),
        Monster(
            id=5361,
            name="Waterfiend",
            combat_level=115,
            hitpoints=95,
            slayer_xp=128,
            slayer_category="Waterfiends",
        ),
        Monster(
            id=5361,
            name="Waterfiend",
            combat_level=115,
            hitpoints=95,
            slayer_xp=128,
            slayer_category="Waterfiends",
        ),
        Monster(
            id=5361,
            name="Waterfiend",
            combat_level=115,
            hitpoints=95,
            slayer_xp=128,
            slayer_category="Waterfiends",
        ),
        Monster(
            id=5361,
            name="Waterfiend",
            combat_level=115,
            hitpoints=95,
            slayer_xp=128,
            slayer_category="Waterfiends",
        ),
        Monster(
            id=5361,
            name="Waterfiend",
            combat_level=115,
            hitpoints=95,
            slayer_xp=128,
            slayer_category="Waterfiends",
        ),
        Monster(
            id=3169,
            name="Aviansie",
            combat_level=69,
            hitpoints=80,
            slayer_xp=86.9,
            slayer_category="Aviansies",
        ),
        Monster(
            id=3169,
            name="Aviansie",
            combat_level=69,
            hitpoints=80,
            slayer_xp=86.9,
            slayer_category="Aviansies",
        ),
        Monster(
            id=3169,
            name="Aviansie",
            combat_level=69,
            hitpoints=80,
            slayer_xp=86.9,
            slayer_category="Aviansies",
        ),
        Monster(
            id=3169,
            name="Aviansie",
            combat_level=69,
            hitpoints=80,
            slayer_xp=86.9,
            slayer_category="Aviansies",
        ),
        Monster(
            id=3169,
            name="Aviansie",
            combat_level=69,
            hitpoints=80,
            slayer_xp=86.9,
            slayer_category="Aviansies",
        ),
        Monster(
            id=3169,
            name="Aviansie",
            combat_level=69,
            hitpoints=80,
            slayer_xp=86.9,
            slayer_category="Aviansies",
        ),
        Monster(
            id=3169,
            name="Aviansie",
            combat_level=69,
            hitpoints=80,
            slayer_xp=86.9,
            slayer_category="Aviansies",
        ),
        Monster(
            id=3169,
            name="Aviansie",
            combat_level=69,
            hitpoints=80,
            slayer_xp=86.9,
            slayer_category="Aviansies",
        ),
        Monster(
            id=2244,
            name="Spiritual warrior",
            combat_level=98,
            hitpoints=96,
            slayer_xp=98.5,
            slayer_category="Spiritual creatures",
        ),
        Monster(
            id=2244,
            name="Spiritual warrior",
            combat_level=98,
            hitpoints=96,
            slayer_xp=98.5,
            slayer_category="Spiritual creatures",
        ),
        Monster(
            id=2244,
            name="Spiritual warrior",
            combat_level=98,
            hitpoints=96,
            slayer_xp=98.5,
            slayer_category="Spiritual creatures",
        ),
        Monster(
            id=2244,
            name="Spiritual warrior",
            combat_level=98,
            hitpoints=96,
            slayer_xp=98.5,
            slayer_category="Spiritual creatures",
        ),
        Monster(
            id=2244,
            name="Spiritual warrior",
            combat_level=98,
            hitpoints=96,
            slayer_xp=98.5,
            slayer_category="Spiritual creatures",
        ),
        Monster(
            id=2244,
            name="Spiritual warrior",
            combat_level=98,
            hitpoints=96,
            slayer_xp=98.5,
            slayer_category="Spiritual creatures",
        ),
        Monster(
            id=2244,
            name="Spiritual warrior",
            combat_level=98,
            hitpoints=96,
            slayer_xp=98.5,
            slayer_category="Spiritual creatures",
        ),
        Monster(
            id=2244,
            name="Spiritual warrior",
            combat_level=98,
            hitpoints=96,
            slayer_xp=98.5,
            slayer_category="Spiritual creatures",
        ),
        Monster(
            id=4527,
            name="Suqah",
            combat_level=111,
            hitpoints=106,
            slayer_xp=106,
            slayer_category="Suqah",
        ),
        Monster(
            id=4527,
            name="Suqah",
            combat_level=111,
            hitpoints=106,
            slayer_xp=106,
            slayer_category="Suqah",
        ),
        Monster(
            id=4527,
            name="Suqah",
            combat_level=111,
            hitpoints=106,
            slayer_xp=106,
            slayer_category="Suqah",
        ),
        Monster(
            id=4527,
            name="Suqah",
            combat_level=111,
            hitpoints=106,
            slayer_xp=106,
            slayer_category="Suqah",
        ),
        Monster(
            id=4527,
            name="Suqah",
            combat_level=111,
            hitpoints=106,
            slayer_xp=106,
            slayer_category="Suqah",
        ),
        Monster(
            id=4527,
            name="Suqah",
            combat_level=111,
            hitpoints=106,
            slayer_xp=106,
            slayer_category="Suqah",
        ),
        Monster(
            id=4527,
            name="Suqah",
            combat_level=111,
            hitpoints=106,
            slayer_xp=106,
            slayer_category="Suqah",
        ),
        Monster(
            id=4527,
            name="Suqah",
            combat_level=111,
            hitpoints=106,
            slayer_xp=106,
            slayer_category="Suqah",
        ),
        Monster(
            id=2359,
            name="Iorwerth Archer",
            combat_level=108,
            hitpoints=104,
            slayer_xp=105,
            slayer_category="Elves",
        ),
        Monster(
            id=2359,
            name="Iorwerth Archer",
            combat_level=108,
            hitpoints=104,
            slayer_xp=105,
            slayer_category="Elves",
        ),
        Monster(
            id=2359,
            name="Iorwerth Archer",
            combat_level=108,
            hitpoints=104,
            slayer_xp=105,
            slayer_category="Elves",
        ),
        Monster(
            id=2359,
            name="Iorwerth Archer",
            combat_level=108,
            hitpoints=104,
            slayer_xp=105,
            slayer_category="Elves",
        ),
        Monster(
            id=2359,
            name="Iorwerth Archer",
            combat_level=108,
            hitpoints=104,
            slayer_xp=105,
            slayer_category="Elves",
        ),
        Monster(
            id=2359,
            name="Iorwerth Archer",
            combat_level=108,
            hitpoints=104,
            slayer_xp=105,
            slayer_category="Elves",
        ),
        Monster(
            id=2359,
            name="Iorwerth Archer",
            combat_level=108,
            hitpoints=104,
            slayer_xp=105,
            slayer_category="Elves",
        ),
        Monster(
            id=2359,
            name="Iorwerth Archer",
            combat_level=108,
            hitpoints=104,
            slayer_xp=105,
            slayer_category="Elves",
        ),
        Monster(
            id=1106,
            name="Mountain troll",
            combat_level=69,
            hitpoints=50,
            slayer_xp=50,
            slayer_category="Trolls",
        ),
        Monster(
            id=1106,
            name="Mountain troll",
            combat_level=69,
            hitpoints=50,
            slayer_xp=50,
            slayer_category="Trolls",
        ),
        Monster(
            id=1106,
            name="Mountain troll",
            combat_level=69,
            hitpoints=50,
            slayer_xp=50,
            slayer_category="Trolls",
        ),
        Monster(
            id=1106,
            name="Mountain troll",
            combat_level=69,
            hitpoints=50,
            slayer_xp=50,
            slayer_category="Trolls",
        ),
        Monster(
            id=1106,
            name="Mountain troll",
            combat_level=69,
            hitpoints=50,
            slayer_xp=50,
            slayer_category="Trolls",
        ),
        Monster(
            id=1106,
            name="Mountain troll",
            combat_level=69,
            hitpoints=50,
            slayer_xp=50,
            slayer_category="Trolls",
        ),
        Monster(
            id=1106,
            name="Mountain troll",
            combat_level=69,
            hitpoints=50,
            slayer_xp=50,
            slayer_category="Trolls",
        ),
        Monster(
            id=1106,
            name="Mountain troll",
            combat_level=69,
            hitpoints=50,
            slayer_xp=50,
            slayer_category="Trolls",
        ),
        Monster(
            id=3347,
            name="Mutated zygomite",
            combat_level=74,
            hitpoints=65,
            slayer_xp=75,
            slayer_category="Mutated zygomites",
        ),
        Monster(
            id=3347,
            name="Mutated zygomite",
            combat_level=74,
            hitpoints=65,
            slayer_xp=75,
            slayer_category="Mutated zygomites",
        ),
        Monster(
            id=3347,
            name="Mutated zygomite",
            combat_level=74,
            hitpoints=65,
            slayer_xp=75,
            slayer_category="Mutated zygomites",
        ),
        Monster(
            id=3347,
            name="Mutated zygomite",
            combat_level=74,
            hitpoints=65,
            slayer_xp=75,
            slayer_category="Mutated zygomites",
        ),
        Monster(
            id=3347,
            name="Mutated zygomite",
            combat_level=74,
            hitpoints=65,
            slayer_xp=75,
            slayer_category="Mutated zygomites",
        ),
        Monster(
            id=3347,
            name="Mutated zygomite",
            combat_level=74,
            hitpoints=65,
            slayer_xp=75,
            slayer_category="Mutated zygomites",
        ),
        Monster(
            id=3347,
            name="Mutated zygomite",
            combat_level=74,
            hitpoints=65,
            slayer_xp=75,
            slayer_category="Mutated zygomites",
        ),
        Monster(
            id=3347,
            name="Mutated zygomite",
            combat_level=74,
            hitpoints=65,
            slayer_xp=75,
            slayer_category="Mutated zygomites",
        ),
        Monster(
            id=2831,
            name="Brine rat",
            combat_level=70,
            hitpoints=50,
            slayer_xp=45,
            slayer_category="Brine rats",
        ),
        Monster(
            id=2831,
            name="Brine rat",
            combat_level=70,
            hitpoints=50,
            slayer_xp=45,
            slayer_category="Brine rats",
        ),
        Monster(
            id=2831,
            name="Brine rat",
            combat_level=70,
            hitpoints=50,
            slayer_xp=45,
            slayer_category="Brine rats",
        ),
        Monster(
            id=2831,
            name="Brine rat",
            combat_level=70,
            hitpoints=50,
            slayer_xp=45,
            slayer_category="Brine rats",
        ),
        Monster(
            id=2831,
            name="Brine rat",
            combat_level=70,
            hitpoints=50,
            slayer_xp=45,
            slayer_category="Brine rats",
        ),
        Monster(
            id=2831,
            name="Brine rat",
            combat_level=70,
            hitpoints=50,
            slayer_xp=45,
            slayer_category="Brine rats",
        ),
        Monster(
            id=2831,
            name="Brine rat",
            combat_level=70,
            hitpoints=50,
            slayer_xp=45,
            slayer_category="Brine rats",
        ),
        Monster(
            id=2831,
            name="Brine rat",
            combat_level=70,
            hitpoints=50,
            slayer_xp=45,
            slayer_category="Brine rats",
        ),
        Monster(
            id=1626,
            name="Turoth",
            combat_level=83,
            hitpoints=76,
            slayer_xp=76,
            slayer_category="Turoth",
        ),
        Monster(
            id=1626,
            name="Turoth",
            combat_level=83,
            hitpoints=76,
            slayer_xp=76,
            slayer_category="Turoth",
        ),
        Monster(
            id=1626,
            name="Turoth",
            combat_level=83,
            hitpoints=76,
            slayer_xp=76,
            slayer_category="Turoth",
        ),
        Monster(
            id=1626,
            name="Turoth",
            combat_level=83,
            hitpoints=76,
            slayer_xp=76,
            slayer_category="Turoth",
        ),
        Monster(
            id=1626,
            name="Turoth",
            combat_level=83,
            hitpoints=76,
            slayer_xp=76,
            slayer_category="Turoth",
        ),
        Monster(
            id=1626,
            name="Turoth",
            combat_level=83,
            hitpoints=76,
            slayer_xp=76,
            slayer_category="Turoth",
        ),
        Monster(
            id=1626,
            name="Turoth",
            combat_level=83,
            hitpoints=76,
            slayer_xp=76,
            slayer_category="Turoth",
        ),
        Monster(
            id=1626,
            name="Turoth",
            combat_level=83,
            hitpoints=76,
            slayer_xp=76,
            slayer_category="Turoth",
        ),
        Monster(
            id=6575,
            name="Scabarite",
            combat_level=73,
            hitpoints=85,
            slayer_xp=85,
            slayer_category="Scabarites",
        ),
        Monster(
            id=6575,
            name="Scabarite",
            combat_level=73,
            hitpoints=85,
            slayer_xp=85,
            slayer_category="Scabarites",
        ),
        Monster(
            id=6575,
            name="Scabarite",
            combat_level=73,
            hitpoints=85,
            slayer_xp=85,
            slayer_category="Scabarites",
        ),
        Monster(
            id=6575,
            name="Scabarite",
            combat_level=73,
            hitpoints=85,
            slayer_xp=85,
            slayer_category="Scabarites",
        ),
        Monster(
            id=6575,
            name="Scabarite",
            combat_level=73,
            hitpoints=85,
            slayer_xp=85,
            slayer_category="Scabarites",
        ),
        Monster(
            id=6575,
            name="Scabarite",
            combat_level=73,
            hitpoints=85,
            slayer_xp=85,
            slayer_category="Scabarites",
        ),
        Monster(
            id=6575,
            name="Scabarite",
            combat_level=73,
            hitpoints=85,
            slayer_xp=85,
            slayer_category="Scabarites",
        ),
        Monster(
            id=6575,
            name="Scabarite",
            combat_level=73,
            hitpoints=85,
            slayer_xp=85,
            slayer_category="Scabarites",
        ),
        Monster(
            id=9999,
            name="Boss",
            combat_level=200,
            hitpoints=500,
            slayer_xp=1000,
            slayer_category="Boss",
        ),
        Monster(
            id=9999,
            name="Boss",
            combat_level=200,
            hitpoints=500,
            slayer_xp=1000,
            slayer_category="Boss",
        ),
        Monster(
            id=9999,
            name="Boss",
            combat_level=200,
            hitpoints=500,
            slayer_xp=1000,
            slayer_category="Boss",
        ),
        Monster(
            id=9999,
            name="Boss",
            combat_level=200,
            hitpoints=500,
            slayer_xp=1000,
            slayer_category="Boss",
        ),
        Monster(
            id=9999,
            name="Boss",
            combat_level=200,
            hitpoints=500,
            slayer_xp=1000,
            slayer_category="Boss",
        ),
        Monster(
            id=9999,
            name="Boss",
            combat_level=200,
            hitpoints=500,
            slayer_xp=1000,
            slayer_category="Boss",
        ),
        Monster(
            id=9999,
            name="Boss",
            combat_level=200,
            hitpoints=500,
            slayer_xp=1000,
            slayer_category="Boss",
        ),
        Monster(
            id=9999,
            name="Boss",
            combat_level=200,
            hitpoints=500,
            slayer_xp=1000,
            slayer_category="Boss",
        ),
    ]
