"""{category_name} monster definitions."""

from backend.models import Monster


def get_demon_monsters() -> list[Monster]:
    """Get {category_name} monster definitions."""
    return [
        Monster(
            id=415,
            name="Abyssal demon",
            combat_level=124,
            hitpoints=150,
            slayer_xp=150,
            slayer_category="Abyssal demons",
            is_demon=True,
        ),
        Monster(
            id=415,
            name="Abyssal demon",
            combat_level=124,
            hitpoints=150,
            slayer_xp=150,
            slayer_category="Abyssal demons",
            is_demon=True,
        ),
        Monster(
            id=415,
            name="Abyssal demon",
            combat_level=124,
            hitpoints=150,
            slayer_xp=150,
            slayer_category="Abyssal demons",
            is_demon=True,
        ),
        Monster(
            id=415,
            name="Abyssal demon",
            combat_level=124,
            hitpoints=150,
            slayer_xp=150,
            slayer_category="Abyssal demons",
            is_demon=True,
        ),
        Monster(
            id=415,
            name="Abyssal demon",
            combat_level=124,
            hitpoints=150,
            slayer_xp=150,
            slayer_category="Abyssal demons",
            is_demon=True,
        ),
        Monster(
            id=415,
            name="Abyssal demon",
            combat_level=124,
            hitpoints=150,
            slayer_xp=150,
            slayer_category="Abyssal demons",
            is_demon=True,
        ),
        Monster(
            id=415,
            name="Abyssal demon",
            combat_level=124,
            hitpoints=150,
            slayer_xp=150,
            slayer_category="Abyssal demons",
            is_demon=True,
        ),
        Monster(
            id=415,
            name="Abyssal demon",
            combat_level=124,
            hitpoints=150,
            slayer_xp=150,
            slayer_category="Abyssal demons",
            is_demon=True,
        ),
        Monster(
            id=415,
            name="Abyssal demon",
            combat_level=124,
            hitpoints=150,
            slayer_xp=150,
            slayer_category="Abyssal demons",
            is_demon=True,
        ),
        Monster(
            id=84,
            name="Greater demon",
            combat_level=92,
            hitpoints=87,
            slayer_xp=87,
            slayer_category="Greater demons",
            is_demon=True,
        ),
        Monster(
            id=84,
            name="Greater demon",
            combat_level=92,
            hitpoints=87,
            slayer_xp=87,
            slayer_category="Greater demons",
            is_demon=True,
        ),
        Monster(
            id=84,
            name="Greater demon",
            combat_level=92,
            hitpoints=87,
            slayer_xp=87,
            slayer_category="Greater demons",
            is_demon=True,
        ),
        Monster(
            id=84,
            name="Greater demon",
            combat_level=92,
            hitpoints=87,
            slayer_xp=87,
            slayer_category="Greater demons",
            is_demon=True,
        ),
        Monster(
            id=84,
            name="Greater demon",
            combat_level=92,
            hitpoints=87,
            slayer_xp=87,
            slayer_category="Greater demons",
            is_demon=True,
        ),
        Monster(
            id=84,
            name="Greater demon",
            combat_level=92,
            hitpoints=87,
            slayer_xp=87,
            slayer_category="Greater demons",
            is_demon=True,
        ),
        Monster(
            id=84,
            name="Greater demon",
            combat_level=92,
            hitpoints=87,
            slayer_xp=87,
            slayer_category="Greater demons",
            is_demon=True,
        ),
        Monster(
            id=84,
            name="Greater demon",
            combat_level=92,
            hitpoints=87,
            slayer_xp=87,
            slayer_category="Greater demons",
            is_demon=True,
        ),
        Monster(
            id=84,
            name="Greater demon",
            combat_level=92,
            hitpoints=87,
            slayer_xp=87,
            slayer_category="Greater demons",
            is_demon=True,
        ),
        Monster(
            id=83,
            name="Black demon",
            combat_level=172,
            hitpoints=157,
            slayer_xp=157,
            slayer_category="Black demons",
            is_demon=True,
        ),
        Monster(
            id=83,
            name="Black demon",
            combat_level=172,
            hitpoints=157,
            slayer_xp=157,
            slayer_category="Black demons",
            is_demon=True,
        ),
        Monster(
            id=83,
            name="Black demon",
            combat_level=172,
            hitpoints=157,
            slayer_xp=157,
            slayer_category="Black demons",
            is_demon=True,
        ),
        Monster(
            id=83,
            name="Black demon",
            combat_level=172,
            hitpoints=157,
            slayer_xp=157,
            slayer_category="Black demons",
            is_demon=True,
        ),
        Monster(
            id=83,
            name="Black demon",
            combat_level=172,
            hitpoints=157,
            slayer_xp=157,
            slayer_category="Black demons",
            is_demon=True,
        ),
        Monster(
            id=83,
            name="Black demon",
            combat_level=172,
            hitpoints=157,
            slayer_xp=157,
            slayer_category="Black demons",
            is_demon=True,
        ),
        Monster(
            id=83,
            name="Black demon",
            combat_level=172,
            hitpoints=157,
            slayer_xp=157,
            slayer_category="Black demons",
            is_demon=True,
        ),
        Monster(
            id=83,
            name="Black demon",
            combat_level=172,
            hitpoints=157,
            slayer_xp=157,
            slayer_category="Black demons",
            is_demon=True,
        ),
        Monster(
            id=83,
            name="Black demon",
            combat_level=172,
            hitpoints=157,
            slayer_xp=157,
            slayer_category="Black demons",
            is_demon=True,
        ),
        Monster(
            id=16,
            name="Nechryael",
            combat_level=115,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Nechryael",
            is_demon=True,
        ),
        Monster(
            id=16,
            name="Nechryael",
            combat_level=115,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Nechryael",
            is_demon=True,
        ),
        Monster(
            id=16,
            name="Nechryael",
            combat_level=115,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Nechryael",
            is_demon=True,
        ),
        Monster(
            id=16,
            name="Nechryael",
            combat_level=115,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Nechryael",
            is_demon=True,
        ),
        Monster(
            id=16,
            name="Nechryael",
            combat_level=115,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Nechryael",
            is_demon=True,
        ),
        Monster(
            id=16,
            name="Nechryael",
            combat_level=115,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Nechryael",
            is_demon=True,
        ),
        Monster(
            id=16,
            name="Nechryael",
            combat_level=115,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Nechryael",
            is_demon=True,
        ),
        Monster(
            id=16,
            name="Nechryael",
            combat_level=115,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Nechryael",
            is_demon=True,
        ),
        Monster(
            id=16,
            name="Nechryael",
            combat_level=115,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Nechryael",
            is_demon=True,
        ),
        Monster(
            id=4,
            name="Hellhound",
            combat_level=122,
            hitpoints=116,
            slayer_xp=116,
            slayer_category="Hellhounds",
            is_demon=True,
        ),
        Monster(
            id=4,
            name="Hellhound",
            combat_level=122,
            hitpoints=116,
            slayer_xp=116,
            slayer_category="Hellhounds",
            is_demon=True,
        ),
        Monster(
            id=4,
            name="Hellhound",
            combat_level=122,
            hitpoints=116,
            slayer_xp=116,
            slayer_category="Hellhounds",
            is_demon=True,
        ),
        Monster(
            id=4,
            name="Hellhound",
            combat_level=122,
            hitpoints=116,
            slayer_xp=116,
            slayer_category="Hellhounds",
            is_demon=True,
        ),
        Monster(
            id=4,
            name="Hellhound",
            combat_level=122,
            hitpoints=116,
            slayer_xp=116,
            slayer_category="Hellhounds",
            is_demon=True,
        ),
        Monster(
            id=4,
            name="Hellhound",
            combat_level=122,
            hitpoints=116,
            slayer_xp=116,
            slayer_category="Hellhounds",
            is_demon=True,
        ),
        Monster(
            id=4,
            name="Hellhound",
            combat_level=122,
            hitpoints=116,
            slayer_xp=116,
            slayer_category="Hellhounds",
            is_demon=True,
        ),
        Monster(
            id=4,
            name="Hellhound",
            combat_level=122,
            hitpoints=116,
            slayer_xp=116,
            slayer_category="Hellhounds",
            is_demon=True,
        ),
        Monster(
            id=4,
            name="Hellhound",
            combat_level=122,
            hitpoints=116,
            slayer_xp=116,
            slayer_category="Hellhounds",
            is_demon=True,
        ),
    ]
