"""{category_name} monster definitions."""

from backend.models import Monster


def get_dragon_monsters() -> list[Monster]:
    """Get {category_name} monster definitions."""
    return [
        Monster(
            id=24,
            name="Hydra",
            combat_level=194,
            hitpoints=300,
            slayer_xp=660,
            slayer_category="Hydras",
            is_dragon=True,
        ),
        Monster(
            id=24,
            name="Hydra",
            combat_level=194,
            hitpoints=300,
            slayer_xp=660,
            slayer_category="Hydras",
            is_dragon=True,
        ),
        Monster(
            id=24,
            name="Hydra",
            combat_level=194,
            hitpoints=300,
            slayer_xp=660,
            slayer_category="Hydras",
            is_dragon=True,
        ),
        Monster(
            id=24,
            name="Hydra",
            combat_level=194,
            hitpoints=300,
            slayer_xp=660,
            slayer_category="Hydras",
            is_dragon=True,
        ),
        Monster(
            id=24,
            name="Hydra",
            combat_level=194,
            hitpoints=300,
            slayer_xp=660,
            slayer_category="Hydras",
            is_dragon=True,
        ),
        Monster(
            id=24,
            name="Hydra",
            combat_level=194,
            hitpoints=300,
            slayer_xp=660,
            slayer_category="Hydras",
            is_dragon=True,
        ),
        Monster(
            id=24,
            name="Hydra",
            combat_level=194,
            hitpoints=300,
            slayer_xp=660,
            slayer_category="Hydras",
            is_dragon=True,
        ),
        Monster(
            id=24,
            name="Hydra",
            combat_level=194,
            hitpoints=300,
            slayer_xp=660,
            slayer_category="Hydras",
            is_dragon=True,
        ),
        Monster(
            id=24,
            name="Hydra",
            combat_level=194,
            hitpoints=300,
            slayer_xp=660,
            slayer_category="Hydras",
            is_dragon=True,
        ),
        Monster(
            id=14,
            name="Wyrm",
            combat_level=62,
            hitpoints=100,
            slayer_xp=133.2,
            slayer_category="Wyrms",
            is_dragon=True,
        ),
        Monster(
            id=14,
            name="Wyrm",
            combat_level=62,
            hitpoints=100,
            slayer_xp=133.2,
            slayer_category="Wyrms",
            is_dragon=True,
        ),
        Monster(
            id=14,
            name="Wyrm",
            combat_level=62,
            hitpoints=100,
            slayer_xp=133.2,
            slayer_category="Wyrms",
            is_dragon=True,
        ),
        Monster(
            id=14,
            name="Wyrm",
            combat_level=62,
            hitpoints=100,
            slayer_xp=133.2,
            slayer_category="Wyrms",
            is_dragon=True,
        ),
        Monster(
            id=14,
            name="Wyrm",
            combat_level=62,
            hitpoints=100,
            slayer_xp=133.2,
            slayer_category="Wyrms",
            is_dragon=True,
        ),
        Monster(
            id=14,
            name="Wyrm",
            combat_level=62,
            hitpoints=100,
            slayer_xp=133.2,
            slayer_category="Wyrms",
            is_dragon=True,
        ),
        Monster(
            id=14,
            name="Wyrm",
            combat_level=62,
            hitpoints=100,
            slayer_xp=133.2,
            slayer_category="Wyrms",
            is_dragon=True,
        ),
        Monster(
            id=14,
            name="Wyrm",
            combat_level=62,
            hitpoints=100,
            slayer_xp=133.2,
            slayer_category="Wyrms",
            is_dragon=True,
        ),
        Monster(
            id=14,
            name="Wyrm",
            combat_level=62,
            hitpoints=100,
            slayer_xp=133.2,
            slayer_category="Wyrms",
            is_dragon=True,
        ),
        Monster(
            id=15,
            name="Drake",
            combat_level=84,
            hitpoints=250,
            slayer_xp=316.8,
            slayer_category="Drakes",
            is_dragon=True,
        ),
        Monster(
            id=15,
            name="Drake",
            combat_level=84,
            hitpoints=250,
            slayer_xp=316.8,
            slayer_category="Drakes",
            is_dragon=True,
        ),
        Monster(
            id=15,
            name="Drake",
            combat_level=84,
            hitpoints=250,
            slayer_xp=316.8,
            slayer_category="Drakes",
            is_dragon=True,
        ),
        Monster(
            id=15,
            name="Drake",
            combat_level=84,
            hitpoints=250,
            slayer_xp=316.8,
            slayer_category="Drakes",
            is_dragon=True,
        ),
        Monster(
            id=15,
            name="Drake",
            combat_level=84,
            hitpoints=250,
            slayer_xp=316.8,
            slayer_category="Drakes",
            is_dragon=True,
        ),
        Monster(
            id=15,
            name="Drake",
            combat_level=84,
            hitpoints=250,
            slayer_xp=316.8,
            slayer_category="Drakes",
            is_dragon=True,
        ),
        Monster(
            id=15,
            name="Drake",
            combat_level=84,
            hitpoints=250,
            slayer_xp=316.8,
            slayer_category="Drakes",
            is_dragon=True,
        ),
        Monster(
            id=15,
            name="Drake",
            combat_level=84,
            hitpoints=250,
            slayer_xp=316.8,
            slayer_category="Drakes",
            is_dragon=True,
        ),
        Monster(
            id=15,
            name="Drake",
            combat_level=84,
            hitpoints=250,
            slayer_xp=316.8,
            slayer_category="Drakes",
            is_dragon=True,
        ),
        Monster(
            id=270,
            name="Bronze dragon",
            combat_level=131,
            hitpoints=80,
            slayer_xp=80,
            slayer_category="Bronze dragons",
            is_dragon=True,
        ),
        Monster(
            id=270,
            name="Bronze dragon",
            combat_level=131,
            hitpoints=80,
            slayer_xp=80,
            slayer_category="Bronze dragons",
            is_dragon=True,
        ),
        Monster(
            id=270,
            name="Bronze dragon",
            combat_level=131,
            hitpoints=80,
            slayer_xp=80,
            slayer_category="Bronze dragons",
            is_dragon=True,
        ),
        Monster(
            id=270,
            name="Bronze dragon",
            combat_level=131,
            hitpoints=80,
            slayer_xp=80,
            slayer_category="Bronze dragons",
            is_dragon=True,
        ),
        Monster(
            id=270,
            name="Bronze dragon",
            combat_level=131,
            hitpoints=80,
            slayer_xp=80,
            slayer_category="Bronze dragons",
            is_dragon=True,
        ),
        Monster(
            id=270,
            name="Bronze dragon",
            combat_level=131,
            hitpoints=80,
            slayer_xp=80,
            slayer_category="Bronze dragons",
            is_dragon=True,
        ),
        Monster(
            id=270,
            name="Bronze dragon",
            combat_level=131,
            hitpoints=80,
            slayer_xp=80,
            slayer_category="Bronze dragons",
            is_dragon=True,
        ),
        Monster(
            id=270,
            name="Bronze dragon",
            combat_level=131,
            hitpoints=80,
            slayer_xp=80,
            slayer_category="Bronze dragons",
            is_dragon=True,
        ),
        Monster(
            id=270,
            name="Bronze dragon",
            combat_level=131,
            hitpoints=80,
            slayer_xp=80,
            slayer_category="Bronze dragons",
            is_dragon=True,
        ),
        Monster(
            id=274,
            name="Iron dragon",
            combat_level=189,
            hitpoints=160,
            slayer_xp=173.2,
            slayer_category="Iron dragons",
            is_dragon=True,
        ),
        Monster(
            id=274,
            name="Iron dragon",
            combat_level=189,
            hitpoints=160,
            slayer_xp=173.2,
            slayer_category="Iron dragons",
            is_dragon=True,
        ),
        Monster(
            id=274,
            name="Iron dragon",
            combat_level=189,
            hitpoints=160,
            slayer_xp=173.2,
            slayer_category="Iron dragons",
            is_dragon=True,
        ),
        Monster(
            id=274,
            name="Iron dragon",
            combat_level=189,
            hitpoints=160,
            slayer_xp=173.2,
            slayer_category="Iron dragons",
            is_dragon=True,
        ),
        Monster(
            id=274,
            name="Iron dragon",
            combat_level=189,
            hitpoints=160,
            slayer_xp=173.2,
            slayer_category="Iron dragons",
            is_dragon=True,
        ),
        Monster(
            id=274,
            name="Iron dragon",
            combat_level=189,
            hitpoints=160,
            slayer_xp=173.2,
            slayer_category="Iron dragons",
            is_dragon=True,
        ),
        Monster(
            id=274,
            name="Iron dragon",
            combat_level=189,
            hitpoints=160,
            slayer_xp=173.2,
            slayer_category="Iron dragons",
            is_dragon=True,
        ),
        Monster(
            id=274,
            name="Iron dragon",
            combat_level=189,
            hitpoints=160,
            slayer_xp=173.2,
            slayer_category="Iron dragons",
            is_dragon=True,
        ),
        Monster(
            id=274,
            name="Iron dragon",
            combat_level=189,
            hitpoints=160,
            slayer_xp=173.2,
            slayer_category="Iron dragons",
            is_dragon=True,
        ),
        Monster(
            id=273,
            name="Steel dragon",
            combat_level=246,
            hitpoints=210,
            slayer_xp=220.2,
            slayer_category="Steel dragons",
            is_dragon=True,
        ),
        Monster(
            id=273,
            name="Steel dragon",
            combat_level=246,
            hitpoints=210,
            slayer_xp=220.2,
            slayer_category="Steel dragons",
            is_dragon=True,
        ),
        Monster(
            id=273,
            name="Steel dragon",
            combat_level=246,
            hitpoints=210,
            slayer_xp=220.2,
            slayer_category="Steel dragons",
            is_dragon=True,
        ),
        Monster(
            id=273,
            name="Steel dragon",
            combat_level=246,
            hitpoints=210,
            slayer_xp=220.2,
            slayer_category="Steel dragons",
            is_dragon=True,
        ),
        Monster(
            id=273,
            name="Steel dragon",
            combat_level=246,
            hitpoints=210,
            slayer_xp=220.2,
            slayer_category="Steel dragons",
            is_dragon=True,
        ),
        Monster(
            id=273,
            name="Steel dragon",
            combat_level=246,
            hitpoints=210,
            slayer_xp=220.2,
            slayer_category="Steel dragons",
            is_dragon=True,
        ),
        Monster(
            id=273,
            name="Steel dragon",
            combat_level=246,
            hitpoints=210,
            slayer_xp=220.2,
            slayer_category="Steel dragons",
            is_dragon=True,
        ),
        Monster(
            id=273,
            name="Steel dragon",
            combat_level=246,
            hitpoints=210,
            slayer_xp=220.2,
            slayer_category="Steel dragons",
            is_dragon=True,
        ),
        Monster(
            id=273,
            name="Steel dragon",
            combat_level=246,
            hitpoints=210,
            slayer_xp=220.2,
            slayer_category="Steel dragons",
            is_dragon=True,
        ),
        Monster(
            id=5362,
            name="Mithril dragon",
            combat_level=304,
            hitpoints=255,
            slayer_xp=273,
            slayer_category="Mithril dragons",
            is_dragon=True,
        ),
        Monster(
            id=5362,
            name="Mithril dragon",
            combat_level=304,
            hitpoints=255,
            slayer_xp=273,
            slayer_category="Mithril dragons",
            is_dragon=True,
        ),
        Monster(
            id=5362,
            name="Mithril dragon",
            combat_level=304,
            hitpoints=255,
            slayer_xp=273,
            slayer_category="Mithril dragons",
            is_dragon=True,
        ),
        Monster(
            id=5362,
            name="Mithril dragon",
            combat_level=304,
            hitpoints=255,
            slayer_xp=273,
            slayer_category="Mithril dragons",
            is_dragon=True,
        ),
        Monster(
            id=5362,
            name="Mithril dragon",
            combat_level=304,
            hitpoints=255,
            slayer_xp=273,
            slayer_category="Mithril dragons",
            is_dragon=True,
        ),
        Monster(
            id=5362,
            name="Mithril dragon",
            combat_level=304,
            hitpoints=255,
            slayer_xp=273,
            slayer_category="Mithril dragons",
            is_dragon=True,
        ),
        Monster(
            id=5362,
            name="Mithril dragon",
            combat_level=304,
            hitpoints=255,
            slayer_xp=273,
            slayer_category="Mithril dragons",
            is_dragon=True,
        ),
        Monster(
            id=5362,
            name="Mithril dragon",
            combat_level=304,
            hitpoints=255,
            slayer_xp=273,
            slayer_category="Mithril dragons",
            is_dragon=True,
        ),
        Monster(
            id=5362,
            name="Mithril dragon",
            combat_level=304,
            hitpoints=255,
            slayer_xp=273,
            slayer_category="Mithril dragons",
            is_dragon=True,
        ),
        Monster(
            id=8090,
            name="Adamant dragon",
            combat_level=338,
            hitpoints=300,
            slayer_xp=331.8,
            slayer_category="Adamant dragons",
            is_dragon=True,
        ),
        Monster(
            id=8090,
            name="Adamant dragon",
            combat_level=338,
            hitpoints=300,
            slayer_xp=331.8,
            slayer_category="Adamant dragons",
            is_dragon=True,
        ),
        Monster(
            id=8090,
            name="Adamant dragon",
            combat_level=338,
            hitpoints=300,
            slayer_xp=331.8,
            slayer_category="Adamant dragons",
            is_dragon=True,
        ),
        Monster(
            id=8090,
            name="Adamant dragon",
            combat_level=338,
            hitpoints=300,
            slayer_xp=331.8,
            slayer_category="Adamant dragons",
            is_dragon=True,
        ),
        Monster(
            id=8090,
            name="Adamant dragon",
            combat_level=338,
            hitpoints=300,
            slayer_xp=331.8,
            slayer_category="Adamant dragons",
            is_dragon=True,
        ),
        Monster(
            id=8090,
            name="Adamant dragon",
            combat_level=338,
            hitpoints=300,
            slayer_xp=331.8,
            slayer_category="Adamant dragons",
            is_dragon=True,
        ),
        Monster(
            id=8090,
            name="Adamant dragon",
            combat_level=338,
            hitpoints=300,
            slayer_xp=331.8,
            slayer_category="Adamant dragons",
            is_dragon=True,
        ),
        Monster(
            id=8090,
            name="Adamant dragon",
            combat_level=338,
            hitpoints=300,
            slayer_xp=331.8,
            slayer_category="Adamant dragons",
            is_dragon=True,
        ),
        Monster(
            id=8090,
            name="Adamant dragon",
            combat_level=338,
            hitpoints=300,
            slayer_xp=331.8,
            slayer_category="Adamant dragons",
            is_dragon=True,
        ),
        Monster(
            id=8091,
            name="Rune dragon",
            combat_level=380,
            hitpoints=330,
            slayer_xp=382.5,
            slayer_category="Rune dragons",
            is_dragon=True,
        ),
        Monster(
            id=8091,
            name="Rune dragon",
            combat_level=380,
            hitpoints=330,
            slayer_xp=382.5,
            slayer_category="Rune dragons",
            is_dragon=True,
        ),
        Monster(
            id=8091,
            name="Rune dragon",
            combat_level=380,
            hitpoints=330,
            slayer_xp=382.5,
            slayer_category="Rune dragons",
            is_dragon=True,
        ),
        Monster(
            id=8091,
            name="Rune dragon",
            combat_level=380,
            hitpoints=330,
            slayer_xp=382.5,
            slayer_category="Rune dragons",
            is_dragon=True,
        ),
        Monster(
            id=8091,
            name="Rune dragon",
            combat_level=380,
            hitpoints=330,
            slayer_xp=382.5,
            slayer_category="Rune dragons",
            is_dragon=True,
        ),
        Monster(
            id=8091,
            name="Rune dragon",
            combat_level=380,
            hitpoints=330,
            slayer_xp=382.5,
            slayer_category="Rune dragons",
            is_dragon=True,
        ),
        Monster(
            id=8091,
            name="Rune dragon",
            combat_level=380,
            hitpoints=330,
            slayer_xp=382.5,
            slayer_category="Rune dragons",
            is_dragon=True,
        ),
        Monster(
            id=8091,
            name="Rune dragon",
            combat_level=380,
            hitpoints=330,
            slayer_xp=382.5,
            slayer_category="Rune dragons",
            is_dragon=True,
        ),
        Monster(
            id=8091,
            name="Rune dragon",
            combat_level=380,
            hitpoints=330,
            slayer_xp=382.5,
            slayer_category="Rune dragons",
            is_dragon=True,
        ),
        Monster(
            id=262,
            name="Black dragon",
            combat_level=227,
            hitpoints=190,
            slayer_xp=199.5,
            slayer_category="Black dragons",
            is_dragon=True,
        ),
        Monster(
            id=262,
            name="Black dragon",
            combat_level=227,
            hitpoints=190,
            slayer_xp=199.5,
            slayer_category="Black dragons",
            is_dragon=True,
        ),
        Monster(
            id=262,
            name="Black dragon",
            combat_level=227,
            hitpoints=190,
            slayer_xp=199.5,
            slayer_category="Black dragons",
            is_dragon=True,
        ),
        Monster(
            id=262,
            name="Black dragon",
            combat_level=227,
            hitpoints=190,
            slayer_xp=199.5,
            slayer_category="Black dragons",
            is_dragon=True,
        ),
        Monster(
            id=262,
            name="Black dragon",
            combat_level=227,
            hitpoints=190,
            slayer_xp=199.5,
            slayer_category="Black dragons",
            is_dragon=True,
        ),
        Monster(
            id=262,
            name="Black dragon",
            combat_level=227,
            hitpoints=190,
            slayer_xp=199.5,
            slayer_category="Black dragons",
            is_dragon=True,
        ),
        Monster(
            id=262,
            name="Black dragon",
            combat_level=227,
            hitpoints=190,
            slayer_xp=199.5,
            slayer_category="Black dragons",
            is_dragon=True,
        ),
        Monster(
            id=262,
            name="Black dragon",
            combat_level=227,
            hitpoints=190,
            slayer_xp=199.5,
            slayer_category="Black dragons",
            is_dragon=True,
        ),
        Monster(
            id=262,
            name="Black dragon",
            combat_level=227,
            hitpoints=190,
            slayer_xp=199.5,
            slayer_category="Black dragons",
            is_dragon=True,
        ),
        Monster(
            id=268,
            name="Blue dragon",
            combat_level=111,
            hitpoints=105,
            slayer_xp=107.5,
            slayer_category="Blue dragons",
            is_dragon=True,
        ),
        Monster(
            id=268,
            name="Blue dragon",
            combat_level=111,
            hitpoints=105,
            slayer_xp=107.5,
            slayer_category="Blue dragons",
            is_dragon=True,
        ),
        Monster(
            id=268,
            name="Blue dragon",
            combat_level=111,
            hitpoints=105,
            slayer_xp=107.5,
            slayer_category="Blue dragons",
            is_dragon=True,
        ),
        Monster(
            id=268,
            name="Blue dragon",
            combat_level=111,
            hitpoints=105,
            slayer_xp=107.5,
            slayer_category="Blue dragons",
            is_dragon=True,
        ),
        Monster(
            id=268,
            name="Blue dragon",
            combat_level=111,
            hitpoints=105,
            slayer_xp=107.5,
            slayer_category="Blue dragons",
            is_dragon=True,
        ),
        Monster(
            id=268,
            name="Blue dragon",
            combat_level=111,
            hitpoints=105,
            slayer_xp=107.5,
            slayer_category="Blue dragons",
            is_dragon=True,
        ),
        Monster(
            id=268,
            name="Blue dragon",
            combat_level=111,
            hitpoints=105,
            slayer_xp=107.5,
            slayer_category="Blue dragons",
            is_dragon=True,
        ),
        Monster(
            id=268,
            name="Blue dragon",
            combat_level=111,
            hitpoints=105,
            slayer_xp=107.5,
            slayer_category="Blue dragons",
            is_dragon=True,
        ),
        Monster(
            id=268,
            name="Blue dragon",
            combat_level=111,
            hitpoints=105,
            slayer_xp=107.5,
            slayer_category="Blue dragons",
            is_dragon=True,
        ),
        Monster(
            id=269,
            name="Red dragon",
            combat_level=152,
            hitpoints=140,
            slayer_xp=145.5,
            slayer_category="Red dragons",
            is_dragon=True,
        ),
        Monster(
            id=269,
            name="Red dragon",
            combat_level=152,
            hitpoints=140,
            slayer_xp=145.5,
            slayer_category="Red dragons",
            is_dragon=True,
        ),
        Monster(
            id=269,
            name="Red dragon",
            combat_level=152,
            hitpoints=140,
            slayer_xp=145.5,
            slayer_category="Red dragons",
            is_dragon=True,
        ),
        Monster(
            id=269,
            name="Red dragon",
            combat_level=152,
            hitpoints=140,
            slayer_xp=145.5,
            slayer_category="Red dragons",
            is_dragon=True,
        ),
        Monster(
            id=269,
            name="Red dragon",
            combat_level=152,
            hitpoints=140,
            slayer_xp=145.5,
            slayer_category="Red dragons",
            is_dragon=True,
        ),
        Monster(
            id=269,
            name="Red dragon",
            combat_level=152,
            hitpoints=140,
            slayer_xp=145.5,
            slayer_category="Red dragons",
            is_dragon=True,
        ),
        Monster(
            id=269,
            name="Red dragon",
            combat_level=152,
            hitpoints=140,
            slayer_xp=145.5,
            slayer_category="Red dragons",
            is_dragon=True,
        ),
        Monster(
            id=269,
            name="Red dragon",
            combat_level=152,
            hitpoints=140,
            slayer_xp=145.5,
            slayer_category="Red dragons",
            is_dragon=True,
        ),
        Monster(
            id=269,
            name="Red dragon",
            combat_level=152,
            hitpoints=140,
            slayer_xp=145.5,
            slayer_category="Red dragons",
            is_dragon=True,
        ),
        Monster(
            id=466,
            name="Skeletal wyvern",
            combat_level=140,
            hitpoints=210,
            slayer_xp=210,
            slayer_category="Skeletal wyverns",
        ),
        Monster(
            id=466,
            name="Skeletal wyvern",
            combat_level=140,
            hitpoints=210,
            slayer_xp=210,
            slayer_category="Skeletal wyverns",
        ),
        Monster(
            id=466,
            name="Skeletal wyvern",
            combat_level=140,
            hitpoints=210,
            slayer_xp=210,
            slayer_category="Skeletal wyverns",
        ),
        Monster(
            id=466,
            name="Skeletal wyvern",
            combat_level=140,
            hitpoints=210,
            slayer_xp=210,
            slayer_category="Skeletal wyverns",
        ),
        Monster(
            id=466,
            name="Skeletal wyvern",
            combat_level=140,
            hitpoints=210,
            slayer_xp=210,
            slayer_category="Skeletal wyverns",
        ),
        Monster(
            id=466,
            name="Skeletal wyvern",
            combat_level=140,
            hitpoints=210,
            slayer_xp=210,
            slayer_category="Skeletal wyverns",
        ),
        Monster(
            id=466,
            name="Skeletal wyvern",
            combat_level=140,
            hitpoints=210,
            slayer_xp=210,
            slayer_category="Skeletal wyverns",
        ),
        Monster(
            id=466,
            name="Skeletal wyvern",
            combat_level=140,
            hitpoints=210,
            slayer_xp=210,
            slayer_category="Skeletal wyverns",
        ),
        Monster(
            id=8071,
            name="Ancient wyvern",
            combat_level=210,
            hitpoints=275,
            slayer_xp=312.3,
            slayer_category="Fossil Island wyverns",
        ),
        Monster(
            id=8071,
            name="Ancient wyvern",
            combat_level=210,
            hitpoints=275,
            slayer_xp=312.3,
            slayer_category="Fossil Island wyverns",
        ),
        Monster(
            id=8071,
            name="Ancient wyvern",
            combat_level=210,
            hitpoints=275,
            slayer_xp=312.3,
            slayer_category="Fossil Island wyverns",
        ),
        Monster(
            id=8071,
            name="Ancient wyvern",
            combat_level=210,
            hitpoints=275,
            slayer_xp=312.3,
            slayer_category="Fossil Island wyverns",
        ),
        Monster(
            id=8071,
            name="Ancient wyvern",
            combat_level=210,
            hitpoints=275,
            slayer_xp=312.3,
            slayer_category="Fossil Island wyverns",
        ),
        Monster(
            id=8071,
            name="Ancient wyvern",
            combat_level=210,
            hitpoints=275,
            slayer_xp=312.3,
            slayer_category="Fossil Island wyverns",
        ),
        Monster(
            id=8071,
            name="Ancient wyvern",
            combat_level=210,
            hitpoints=275,
            slayer_xp=312.3,
            slayer_category="Fossil Island wyverns",
        ),
        Monster(
            id=8071,
            name="Ancient wyvern",
            combat_level=210,
            hitpoints=275,
            slayer_xp=312.3,
            slayer_category="Fossil Island wyverns",
        ),
        Monster(
            id=2190,
            name="TzHaar-Ket",
            combat_level=149,
            hitpoints=130,
            slayer_xp=104,
            slayer_category="TzHaar",
        ),
        Monster(
            id=2190,
            name="TzHaar-Ket",
            combat_level=149,
            hitpoints=130,
            slayer_xp=104,
            slayer_category="TzHaar",
        ),
        Monster(
            id=2190,
            name="TzHaar-Ket",
            combat_level=149,
            hitpoints=130,
            slayer_xp=104,
            slayer_category="TzHaar",
        ),
        Monster(
            id=2190,
            name="TzHaar-Ket",
            combat_level=149,
            hitpoints=130,
            slayer_xp=104,
            slayer_category="TzHaar",
        ),
        Monster(
            id=2190,
            name="TzHaar-Ket",
            combat_level=149,
            hitpoints=130,
            slayer_xp=104,
            slayer_category="TzHaar",
        ),
        Monster(
            id=2190,
            name="TzHaar-Ket",
            combat_level=149,
            hitpoints=130,
            slayer_xp=104,
            slayer_category="TzHaar",
        ),
        Monster(
            id=2190,
            name="TzHaar-Ket",
            combat_level=149,
            hitpoints=130,
            slayer_xp=104,
            slayer_category="TzHaar",
        ),
        Monster(
            id=2190,
            name="TzHaar-Ket",
            combat_level=149,
            hitpoints=130,
            slayer_xp=104,
            slayer_category="TzHaar",
        ),
        Monster(
            id=109,
            name="Fire giant",
            combat_level=86,
            hitpoints=111,
            slayer_xp=111,
            slayer_category="Fire giants",
        ),
        Monster(
            id=109,
            name="Fire giant",
            combat_level=86,
            hitpoints=111,
            slayer_xp=111,
            slayer_category="Fire giants",
        ),
        Monster(
            id=109,
            name="Fire giant",
            combat_level=86,
            hitpoints=111,
            slayer_xp=111,
            slayer_category="Fire giants",
        ),
        Monster(
            id=109,
            name="Fire giant",
            combat_level=86,
            hitpoints=111,
            slayer_xp=111,
            slayer_category="Fire giants",
        ),
        Monster(
            id=109,
            name="Fire giant",
            combat_level=86,
            hitpoints=111,
            slayer_xp=111,
            slayer_category="Fire giants",
        ),
        Monster(
            id=109,
            name="Fire giant",
            combat_level=86,
            hitpoints=111,
            slayer_xp=111,
            slayer_category="Fire giants",
        ),
        Monster(
            id=109,
            name="Fire giant",
            combat_level=86,
            hitpoints=111,
            slayer_xp=111,
            slayer_category="Fire giants",
        ),
        Monster(
            id=109,
            name="Fire giant",
            combat_level=86,
            hitpoints=111,
            slayer_xp=111,
            slayer_category="Fire giants",
        ),
    ]
