"""{category_name} monster definitions."""

from backend.models import Monster


def get_undead_monsters() -> list[Monster]:
    """Get {category_name} monster definitions."""
    return [
        Monster(
            id=11,
            name="Aberrant spectre",
            combat_level=96,
            hitpoints=90,
            slayer_xp=90,
            slayer_category="Aberrant spectres",
        ),
        Monster(
            id=11,
            name="Aberrant spectre",
            combat_level=96,
            hitpoints=90,
            slayer_xp=90,
            slayer_category="Aberrant spectres",
        ),
        Monster(
            id=11,
            name="Aberrant spectre",
            combat_level=96,
            hitpoints=90,
            slayer_xp=90,
            slayer_category="Aberrant spectres",
        ),
        Monster(
            id=11,
            name="Aberrant spectre",
            combat_level=96,
            hitpoints=90,
            slayer_xp=90,
            slayer_category="Aberrant spectres",
        ),
        Monster(
            id=11,
            name="Aberrant spectre",
            combat_level=96,
            hitpoints=90,
            slayer_xp=90,
            slayer_category="Aberrant spectres",
        ),
        Monster(
            id=11,
            name="Aberrant spectre",
            combat_level=96,
            hitpoints=90,
            slayer_xp=90,
            slayer_category="Aberrant spectres",
        ),
        Monster(
            id=11,
            name="Aberrant spectre",
            combat_level=96,
            hitpoints=90,
            slayer_xp=90,
            slayer_category="Aberrant spectres",
        ),
        Monster(
            id=11,
            name="Aberrant spectre",
            combat_level=96,
            hitpoints=90,
            slayer_xp=90,
            slayer_category="Aberrant spectres",
        ),
        Monster(
            id=90,
            name="Ankou",
            combat_level=86,
            hitpoints=60,
            slayer_xp=60,
            slayer_category="Ankou",
        ),
        Monster(
            id=90,
            name="Ankou",
            combat_level=86,
            hitpoints=60,
            slayer_xp=60,
            slayer_category="Ankou",
        ),
        Monster(
            id=90,
            name="Ankou",
            combat_level=86,
            hitpoints=60,
            slayer_xp=60,
            slayer_category="Ankou",
        ),
        Monster(
            id=90,
            name="Ankou",
            combat_level=86,
            hitpoints=60,
            slayer_xp=60,
            slayer_category="Ankou",
        ),
        Monster(
            id=90,
            name="Ankou",
            combat_level=86,
            hitpoints=60,
            slayer_xp=60,
            slayer_category="Ankou",
        ),
        Monster(
            id=90,
            name="Ankou",
            combat_level=86,
            hitpoints=60,
            slayer_xp=60,
            slayer_category="Ankou",
        ),
        Monster(
            id=90,
            name="Ankou",
            combat_level=86,
            hitpoints=60,
            slayer_xp=60,
            slayer_category="Ankou",
        ),
        Monster(
            id=90,
            name="Ankou",
            combat_level=86,
            hitpoints=60,
            slayer_xp=60,
            slayer_category="Ankou",
        ),
        Monster(
            id=120,
            name="Bloodveld",
            combat_level=76,
            hitpoints=120,
            slayer_xp=120,
            slayer_category="Bloodvelds",
        ),
        Monster(
            id=120,
            name="Bloodveld",
            combat_level=76,
            hitpoints=120,
            slayer_xp=120,
            slayer_category="Bloodvelds",
        ),
        Monster(
            id=120,
            name="Bloodveld",
            combat_level=76,
            hitpoints=120,
            slayer_xp=120,
            slayer_category="Bloodvelds",
        ),
        Monster(
            id=120,
            name="Bloodveld",
            combat_level=76,
            hitpoints=120,
            slayer_xp=120,
            slayer_category="Bloodvelds",
        ),
        Monster(
            id=120,
            name="Bloodveld",
            combat_level=76,
            hitpoints=120,
            slayer_xp=120,
            slayer_category="Bloodvelds",
        ),
        Monster(
            id=120,
            name="Bloodveld",
            combat_level=76,
            hitpoints=120,
            slayer_xp=120,
            slayer_category="Bloodvelds",
        ),
        Monster(
            id=120,
            name="Bloodveld",
            combat_level=76,
            hitpoints=120,
            slayer_xp=120,
            slayer_category="Bloodvelds",
        ),
        Monster(
            id=120,
            name="Bloodveld",
            combat_level=76,
            hitpoints=120,
            slayer_xp=120,
            slayer_category="Bloodvelds",
        ),
        Monster(
            id=498,
            name="Smoke devil",
            combat_level=160,
            hitpoints=185,
            slayer_xp=185,
            slayer_category="Smoke devils",
        ),
        Monster(
            id=498,
            name="Smoke devil",
            combat_level=160,
            hitpoints=185,
            slayer_xp=185,
            slayer_category="Smoke devils",
        ),
        Monster(
            id=498,
            name="Smoke devil",
            combat_level=160,
            hitpoints=185,
            slayer_xp=185,
            slayer_category="Smoke devils",
        ),
        Monster(
            id=498,
            name="Smoke devil",
            combat_level=160,
            hitpoints=185,
            slayer_xp=185,
            slayer_category="Smoke devils",
        ),
        Monster(
            id=498,
            name="Smoke devil",
            combat_level=160,
            hitpoints=185,
            slayer_xp=185,
            slayer_category="Smoke devils",
        ),
        Monster(
            id=498,
            name="Smoke devil",
            combat_level=160,
            hitpoints=185,
            slayer_xp=185,
            slayer_category="Smoke devils",
        ),
        Monster(
            id=498,
            name="Smoke devil",
            combat_level=160,
            hitpoints=185,
            slayer_xp=185,
            slayer_category="Smoke devils",
        ),
        Monster(
            id=498,
            name="Smoke devil",
            combat_level=160,
            hitpoints=185,
            slayer_xp=185,
            slayer_category="Smoke devils",
        ),
        Monster(
            id=9,
            name="Dust devil",
            combat_level=93,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Dust devils",
        ),
        Monster(
            id=9,
            name="Dust devil",
            combat_level=93,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Dust devils",
        ),
        Monster(
            id=9,
            name="Dust devil",
            combat_level=93,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Dust devils",
        ),
        Monster(
            id=9,
            name="Dust devil",
            combat_level=93,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Dust devils",
        ),
        Monster(
            id=9,
            name="Dust devil",
            combat_level=93,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Dust devils",
        ),
        Monster(
            id=9,
            name="Dust devil",
            combat_level=93,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Dust devils",
        ),
        Monster(
            id=9,
            name="Dust devil",
            combat_level=93,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Dust devils",
        ),
        Monster(
            id=9,
            name="Dust devil",
            combat_level=93,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Dust devils",
        ),
        Monster(
            id=122,
            name="Gargoyle",
            combat_level=111,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Gargoyles",
        ),
        Monster(
            id=122,
            name="Gargoyle",
            combat_level=111,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Gargoyles",
        ),
        Monster(
            id=122,
            name="Gargoyle",
            combat_level=111,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Gargoyles",
        ),
        Monster(
            id=122,
            name="Gargoyle",
            combat_level=111,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Gargoyles",
        ),
        Monster(
            id=122,
            name="Gargoyle",
            combat_level=111,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Gargoyles",
        ),
        Monster(
            id=122,
            name="Gargoyle",
            combat_level=111,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Gargoyles",
        ),
        Monster(
            id=122,
            name="Gargoyle",
            combat_level=111,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Gargoyles",
        ),
        Monster(
            id=122,
            name="Gargoyle",
            combat_level=111,
            hitpoints=105,
            slayer_xp=105,
            slayer_category="Gargoyles",
        ),
        Monster(
            id=54,
            name="Dagannoth",
            combat_level=90,
            hitpoints=70,
            slayer_xp=70,
            slayer_category="Dagannoth",
        ),
        Monster(
            id=54,
            name="Dagannoth",
            combat_level=90,
            hitpoints=70,
            slayer_xp=70,
            slayer_category="Dagannoth",
        ),
        Monster(
            id=54,
            name="Dagannoth",
            combat_level=90,
            hitpoints=70,
            slayer_xp=70,
            slayer_category="Dagannoth",
        ),
        Monster(
            id=54,
            name="Dagannoth",
            combat_level=90,
            hitpoints=70,
            slayer_xp=70,
            slayer_category="Dagannoth",
        ),
        Monster(
            id=54,
            name="Dagannoth",
            combat_level=90,
            hitpoints=70,
            slayer_xp=70,
            slayer_category="Dagannoth",
        ),
        Monster(
            id=54,
            name="Dagannoth",
            combat_level=90,
            hitpoints=70,
            slayer_xp=70,
            slayer_category="Dagannoth",
        ),
        Monster(
            id=54,
            name="Dagannoth",
            combat_level=90,
            hitpoints=70,
            slayer_xp=70,
            slayer_category="Dagannoth",
        ),
        Monster(
            id=54,
            name="Dagannoth",
            combat_level=90,
            hitpoints=70,
            slayer_xp=70,
            slayer_category="Dagannoth",
        ),
        Monster(
            id=10,
            name="Kalphite",
            combat_level=28,
            hitpoints=40,
            slayer_xp=40,
            slayer_category="Kalphite",
            is_kalphite=True,
        ),
        Monster(
            id=10,
            name="Kalphite",
            combat_level=28,
            hitpoints=40,
            slayer_xp=40,
            slayer_category="Kalphite",
            is_kalphite=True,
        ),
        Monster(
            id=10,
            name="Kalphite",
            combat_level=28,
            hitpoints=40,
            slayer_xp=40,
            slayer_category="Kalphite",
            is_kalphite=True,
        ),
        Monster(
            id=10,
            name="Kalphite",
            combat_level=28,
            hitpoints=40,
            slayer_xp=40,
            slayer_category="Kalphite",
            is_kalphite=True,
        ),
        Monster(
            id=10,
            name="Kalphite",
            combat_level=28,
            hitpoints=40,
            slayer_xp=40,
            slayer_category="Kalphite",
            is_kalphite=True,
        ),
        Monster(
            id=10,
            name="Kalphite",
            combat_level=28,
            hitpoints=40,
            slayer_xp=40,
            slayer_category="Kalphite",
            is_kalphite=True,
        ),
        Monster(
            id=10,
            name="Kalphite",
            combat_level=28,
            hitpoints=40,
            slayer_xp=40,
            slayer_category="Kalphite",
            is_kalphite=True,
        ),
        Monster(
            id=10,
            name="Kalphite",
            combat_level=28,
            hitpoints=40,
            slayer_xp=40,
            slayer_category="Kalphite",
            is_kalphite=True,
        ),
        Monster(
            id=10,
            name="Kalphite",
            combat_level=28,
            hitpoints=40,
            slayer_xp=40,
            slayer_category="Kalphite",
            is_kalphite=True,
        ),
        Monster(
            id=31,
            name="Kraken",
            combat_level=291,
            hitpoints=255,
            slayer_xp=255,
            slayer_category="Kraken",
        ),
        Monster(
            id=31,
            name="Kraken",
            combat_level=291,
            hitpoints=255,
            slayer_xp=255,
            slayer_category="Kraken",
        ),
        Monster(
            id=31,
            name="Kraken",
            combat_level=291,
            hitpoints=255,
            slayer_xp=255,
            slayer_category="Kraken",
        ),
        Monster(
            id=31,
            name="Kraken",
            combat_level=291,
            hitpoints=255,
            slayer_xp=255,
            slayer_category="Kraken",
        ),
        Monster(
            id=31,
            name="Kraken",
            combat_level=291,
            hitpoints=255,
            slayer_xp=255,
            slayer_category="Kraken",
        ),
        Monster(
            id=31,
            name="Kraken",
            combat_level=291,
            hitpoints=255,
            slayer_xp=255,
            slayer_category="Kraken",
        ),
        Monster(
            id=31,
            name="Kraken",
            combat_level=291,
            hitpoints=255,
            slayer_xp=255,
            slayer_category="Kraken",
        ),
        Monster(
            id=31,
            name="Kraken",
            combat_level=291,
            hitpoints=255,
            slayer_xp=255,
            slayer_category="Kraken",
        ),
        Monster(
            id=32,
            name="Cave kraken",
            combat_level=127,
            hitpoints=125,
            slayer_xp=125,
            slayer_category="Cave kraken",
        ),
        Monster(
            id=32,
            name="Cave kraken",
            combat_level=127,
            hitpoints=125,
            slayer_xp=125,
            slayer_category="Cave kraken",
        ),
        Monster(
            id=32,
            name="Cave kraken",
            combat_level=127,
            hitpoints=125,
            slayer_xp=125,
            slayer_category="Cave kraken",
        ),
        Monster(
            id=32,
            name="Cave kraken",
            combat_level=127,
            hitpoints=125,
            slayer_xp=125,
            slayer_category="Cave kraken",
        ),
        Monster(
            id=32,
            name="Cave kraken",
            combat_level=127,
            hitpoints=125,
            slayer_xp=125,
            slayer_category="Cave kraken",
        ),
        Monster(
            id=32,
            name="Cave kraken",
            combat_level=127,
            hitpoints=125,
            slayer_xp=125,
            slayer_category="Cave kraken",
        ),
        Monster(
            id=32,
            name="Cave kraken",
            combat_level=127,
            hitpoints=125,
            slayer_xp=125,
            slayer_category="Cave kraken",
        ),
        Monster(
            id=32,
            name="Cave kraken",
            combat_level=127,
            hitpoints=125,
            slayer_xp=125,
            slayer_category="Cave kraken",
        ),
    ]
